### ISSUE TITLE
Test Failure (nng.tcp6) - Debian s390x platform

### ISSUE THREAD

**Issue by shikokuchuo** [nanomsg/nng#1739] opened 2023-12-20 13:15 UTC
**Describe the bug**

The automated Debian packaging fails on this one platform (s390x), and is preventing migration of packages to the new release.

The following test fails:
64 - nng.tcp6

**To Reproduce**

For the build log please see https://buildd.debian.org/status/fetch.php?pkg=nng&arch=s390x&ver=1.6.0-1&stamp=1701910216&raw=0

**Environment Details**

 - NNG version: 1.6.0
 - Operating system and version: Debian sid
 - Compiler and language used: gcc 13.2.0

**Additional context**

Just pointing this out. May not be worth addressing directly, but perhaps there is something to make this test more robust for the next release.

**Comment by shikokuchuo** [comment] 2023-12-26 17:13
Nothing I can find to suggest that it does not. In fact, it only fails a few of the tests, so it's not as straightforward as I had thought.

An option might be (if really outside of our control) to just report verbosely but not actually have them fail.

Having said that, it seems that the package has now been accepted and progressed to 'testing' (I guess the Debian maintainer has intervened). It is such a niche platform that perhaps there is nothing to be done, so do feel free to close the issue as resolved even if you decide to make no changes

**Comment by gdamore** [comment] 2023-12-29 23:54
Hm ... I'll leave this open for now -- the suite needs to be rewritten anyway, and we should figure out how to do a better job of discovering IPv6 and skipping it the system has no support for it (or is not configured with it).

**Comment by gdamore** [comment] 2024-02-25 21:44
Actually this is a dupe of #1496 - so closing this one.

**Closed by gdamore** 2024-02-25 21:44 UTC
