### ISSUE TITLE
[Question] is nng production ready?

### ISSUE THREAD

**Issue by 50hz** [nanomsg/nng#603] opened 2018-07-20 06:33 UTC
may I asked if NNG production ready? I know this is a reimplementation of nanomsg which kind of implying its less mature than nanomsg but I am not quite sure what is the current status of nng, is it production ready? shall I skip nanomsg and start building stuff upon nng directly? thanks

**Comment by gdamore** [comment] 2018-07-20 07:11
I consider NNG to be production ready, yes.  While it is younger than nanomsg, it was architected with an eye to being production ready from the start, and consequently NNG is actually more stable than nanomsg (in that it is less likely to crash, and hardened against various error conditions, etc.)

NNG is more actively being developed, and while it is not 100% feature equivalent to libnanomsg, for the vast majority of users all of the functionality needed is present and stable.  (And of course, NNG has many additional capabilities that nanomsg lacks.)

**Comment by gdamore** [comment] 2018-07-20 07:13
I'm closing this as its a question (answered), and not a bug or enhancement request.  You can also ask questions on the mailing list (nanomsg@freelists.org) or in our gitter chat.

**Closed by gdamore** 2018-07-20 07:13 UTC
Labels: question

**Comment by 50hz** [comment] 2018-07-20 15:07
thanks for clarifying and the tips on gitter/mail-list
