### ISSUE TITLE
Build with mbedtls having error

### ISSUE THREAD

**Issue by jlixyz** [nanomsg/nng#1002] opened 2019-10-21 05:57 UTC
I followed the document to build the NNG with mbedtls but got the error:

error: unknown type name ‘mbedtls_x509_crt’

I'm sure that the mbedtls has been installed at /usr/local

Seems the mbedtls include can't be found. Does anyone get this error? Thanks.

**Comment by gdamore** [comment] 2019-10-21 07:23
Can you list which version of mbedtls you are using and also how you compiled specifically?

**Comment by jlixyz** [comment] 2019-10-21 08:24
@gdamore For mbedtls, i got the latest and built with cmake:
mkdir build
cd build
cmake ..
make install

After install, I can see all the mbedtls include and lib under /usr/local

For nng, I exactly followed the build steps in the doc with cmake and enabled mbedtls in cmake parameter.

BTW, when mbedtls is not enabled, the build is successful.

**Comment by gdamore** [comment] 2019-10-21 16:07
It's possible that the mbedTLS API has changed somehow.  Let me investigate.

**Comment by gdamore** [comment] 2019-10-21 16:10
Not it's still there... but maybe we need to add a header file to include the mbedtls/x509_crt.h header file... I'm not sure.  I can't reproduce right now, but you could try adding that as a #include to the file that generates the warning.

**Comment by jlixyz** [comment] 2019-10-21 22:35
@gdamore Including mbedtls/x509_crt.h in tls.c fixed the issued. Will you add this fix to the repo? Thanks

**Comment by gdamore** [comment] 2019-10-21 23:54
Probably yes -- I want to make sure that this is the correct way going forward -- so stay tuned.

**Comment by gdamore** [comment] 2019-11-10 13:40
So I did a little more investigation.  Modern mbedtls does not need this -- *provided* you have configured it properly with support for X509.  In particular, you need the MBEDTLS_X509_CRT_PARSE_C option.  That's completely required, because we pass X509 PEM files, and without that option you won't be able to load any certificates.

If you want to run completely without certificates (insecure mode only -- *very* unrecommended!!) then we could add an option for that, which removed the entire x509 hook.  But that's a lot of code for little real benefit.

Yes, TLS could be configured with pre-shared keys, but we don't support that -- and I've never seen it in the wild.

So please go back and check how you configured mbedTLS.

**Comment by gdamore** [comment] 2019-12-22 08:32
I'm closing for now... this was almost certainly a config error , and no feedback from the submitter.

**Closed by gdamore** 2019-12-22 08:32 UTC
Labels: feedback, tls
