### ISSUE TITLE
Windows version runs poorly in VM with only one core

### ISSUE THREAD

**Issue by JoernHbg** [nanomsg/nng#310] opened 2018-03-26 15:17 UTC
NNG 0.6.0, Windows 64 bit. Using Req/Rep, independent of transport.

The message throughput of nng drops by at least one order of magnitude if there if only one hardware thread available for the process.

I suspect the cause is the use of the slim reader/writer lock as the basic locking mechanism. Using spinlocks makes little sense if there is only one processor, so maybe there needs to be an option to use a locking mechanism that causes task switches without delay if there is only one processor.

I remember that in the times of the Pentium-2 there used to be a single-processor-version of the Windows NT kernel where the ciritical sections had the spin time set to zero.

Please note that I'm not 100% sure that what I'm saying here is correct. Some research is in order before any implementation is begun.

**Comment by gdamore** [comment] 2018-03-26 15:33
I would *hope* that Windows designs would be smart enough to not spin if there is only one core.  In fact, if there is only one core, the locks should simply devolve to no-ops, because there is no chance for contention.  (Maybe not though? Do Windows threads still pre-empt when single core?  I guess so...)

The current NNG design does depend fairly heavily on threading, so it could be that this just hurts much worse on single core systems.

I'm not too familiar with performance analysis on Windows...  if you are in a position to look further, I'd be grateful.

**Comment by gdamore** [comment] 2018-03-26 19:36
Yeah, this actually *used* to be CriticalSections -- I switched to Slim because it seemed to be lighter weight, and more performant.  Plus, and this is key, the slim locks can be allocated statically -- I rely on this in one key place in the startup code.

If CritSecs make more sense on single core systems, we could actually modify the code so that it detects that case, and uses critical sections instead when only a single core is present.

Btw, I wonder if this explains some other horrible long setup times I've seen in my CI infrastructure...  I just assumed that their hosting infra and Windows combined was leading to craptastic performance.  Now I'm wondering...

Does microsoft give any guidance on when to use slim locks vs critical sections?

**Comment by JoernHbg** [comment] 2018-03-27 08:39
Well, there is some info, for instance
https://msdn.microsoft.com/en-gb/magazine/jj721588.aspx
This explains the motive behind slim locks: If you have more and more cores, the chance that the backup mechanism of the CriticalSection is actually used approaches zero. And the backup mechanism used to be large. (note: The CriticalSection has been changed several times since Windows NT 3). So, there is a desire to lower the amount of resources used. Unfortunately, the article doesn’t talk about the number of cores available.

More internals here: http://joeduffyblog.com/2006/11/28/windows-keyed-events-critical-sections-and-new-vista-synchronization-features/

Direct Guidance from Microsoft… no. At least nothing that I have found.
And Google doesn’t have much to say about the “one core” case. I fear that we need the experiment.

Jörn

Von: gdamore [mailto:notifications@github.com]
Gesendet: Montag, 26. März 2018 21:37
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] Windows version runs poorly in VM with only one core (#310)


Yeah, this actually used to be CriticalSections -- I switched to Slim because it seemed to be lighter weight, and more performant. Plus, and this is key, the slim locks can be allocated statically -- I rely on this in one key place in the startup code.

If CritSecs make more sense on single core systems, we could actually modify the code so that it detects that case, and uses critical sections instead when only a single core is present.

Btw, I wonder if this explains some other horrible long setup times I've seen in my CI infrastructure... I just assumed that their hosting infra and Windows combined was leading to craptastic performance. Now I'm wondering...

Does microsoft give any guidance on when to use slim locks vs critical sections?

**Comment by gdamore** [comment] 2018-03-30 19:45
So critical sections have a tunable spin count, but ignore the spin count when on single core.  I can't imagine that slim locks don't behave the same way?? I mean spinning on a single core system is just plain stupid.  Unless the problem is that your VM only has a single real CPU, but the VM is emulating multiple CPUs.. in which case you're probably screwed.

Anyway, I've made some other performance related changes aimed at reducing the number of context switches.  If you can test again, I'd appreciate it!

Also, I have some more changes coming for REQ/REP.  REP in particular is known to have a bug where it can discard messages when it should not -- hitting this requires the receive pipe to be unavailable to handle inbound messages, which normally should not occur without a device proxy, but its possible that you are hitting this in your single core system more easily.

A simple way to test that is to change the pipe queue depth in the REP socket to something larger -- it defaults to 2 but perhaps in your system a deeper queue will help?  Try setting it to 64.  It should be harmless to make this pretty deep.

**Comment by JoernHbg** [comment] 2018-04-03 08:09
OK, say when the changes are checked into the master.

I also managed to do one short session with the profiler, and that was slightly alarming as well. On a normal multi-core machine, I managed to get 60% of total CPU time spend in the slim read/writer spin.
I have a hunch that it spins the spin lock not only in case of a lock contest, but also when it’s doing a genuine wait. As in, wait for the next message to arrive. But I have to take the next version into use and try again.
No use working on 0.7.0 with this.

Jörn


Von: gdamore [mailto:notifications@github.com]
Gesendet: Freitag, 30. März 2018 21:46
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] Windows version runs poorly in VM with only one core (#310)


So critical sections have a tunable spin count, but ignore the spin count when on single core. I can't imagine that slim locks don't behave the same way?? I mean spinning on a single core system is just plain stupid. Unless the problem is that your VM only has a single real CPU, but the VM is emulating multiple CPUs.. in which case you're probably screwed.

Anyway, I've made some other performance related changes aimed at reducing the number of context switches. If you can test again, I'd appreciate it!

Also, I have some more changes coming for REQ/REP. REP in particular is known to have a bug where it can discard messages when it should not -- hitting this requires the receive pipe to be unavailable to handle inbound messages, which normally should not occur without a device proxy, but its possible that you are hitting this in your single core system more easily.

A simple way to test that is to change the pipe queue depth in the REP socket to something larger -- it defaults to 2 but perhaps in your system a deeper queue will help? Try setting it to 64. It should be harmless to make this pretty deep.

**Comment by gdamore** [comment] 2018-04-04 16:05
I suspect #327 and #328 will help a bit here. Naively, I assumed that QueryPerformanceCounter didn't suck.  I was wrong.  (I was thinking this boiled down to just rdtsc... but it appears to be a bit more heavy weight than that -- probably owing to a need to normalize to real time, and potentially synchronize different values across different processors in SMP systems.)

**Comment by JoernHbg** [comment] 2018-04-06 13:46
This indeed helped, but not much.

Looking at the output here, one of the biggest offenders inside the nni_aoi_lk seems to be the call to nni_task_dispatch(&aio->a_task); in the function  nni_aio_finish_impl.
It is possible to move that out of the nni_aio_lk? Because that does spin cycles on its own.

Jörn

Von: gdamore [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. April 2018 18:05
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] Windows version runs poorly in VM with only one core (#310)


I suspect #327<https://github.com/nanomsg/nng/issues/327> and #328<https://github.com/nanomsg/nng/issues/328> will help a bit here. Naively, I assumed that QueryPerformanceCounter didn't suck. I was wrong. (I was thinking this boiled down to just rdtsc... but it appears to be a bit more heavy weight than that -- probably owing to a need to normalize to real time, and potentially synchronize different values across different processors in SMP systems.)

**Comment by markfsanderson** [comment] 2018-04-12 03:29
OSR has an interesting article a similar issue:  http://www.osronline.com/article.cfm?article=561

**Comment by gdamore** [comment] 2018-04-30 16:28
See also #339 -- I suspect that fixing that would help here immensely.

**Comment by gdamore** [comment] 2018-05-04 15:15
I need to learn more about profiling on Windows.  The fact that you're seeing a lot of spin activity strongly indicates that slim locks spin always on contention, and on a single core system they really should never spin.  The other thing it indicates is that there *is* contention here.

Stay tuned.

**Comment by gdamore** [comment] 2018-05-15 08:55
@JoernHbg  Can you have another go at this?  I've done a lot that I think should reduce lock contention.  I think its likely that the problems we had were due to contention, and in those cases the SlimLock may do some ugly things with spinning.  If the locks are uncontended this should not be a problem (given a sane implementation).  Arguably it wouldn't be a problem even with contention if the underlying implementation understood that it was uniprocessor and didn't spin stupidly.

**Comment by JoernHbg** [comment] 2018-05-15 09:30
We can, but if we want to do this in an orderly fashion, I’d need to know what question you have and what you want to have tested.

For instance, do you want before/after comparisons? detailed profiler output? Just “total time spent” numbers?
Or just state your test requirements.

I can of course just run some random test again but I fear the outcome would be “sure looks different now”.

Jörn

Von: gdamore [mailto:notifications@github.com]
Gesendet: Dienstag, 15. Mai 2018 10:56
An: nanomsg/nng
Cc: Sierwald, Jörn; Mention
Betreff: Re: [nanomsg/nng] Windows version runs poorly in VM with only one core (#310)


@JoernHbg<https://github.com/JoernHbg> Can you have another go at this? I've done a lot that I think should reduce lock contention. I think its likely that the problems we had were due to contention, and in those cases the SlimLock may do some ugly things with spinning. If the locks are uncontended this should not be a problem (given a sane implementation). Arguably it wouldn't be a problem even with contention if the underlying implementation understood that it was uniprocessor and didn't spin stupidly.

**Comment by gdamore** [comment] 2018-05-16 02:27
A before and after comparison would be ideal.  I expect that a single core will perform worse than two cores.  If it performs more than twice as a badly (after normalizing for CPU speed), then we have a serious issue.

**Comment by gdamore** [comment] 2018-06-15 19:54
I've made some further changes that should cause the number of concurrent threads in this case to be somewhat smaller.  This may have helped.

**Comment by gdamore** [comment] 2018-07-07 04:17
#568 also represents some substantial refactoring.  There is still work to do of course.

**Comment by gdamore** [comment] 2019-12-12 02:14
I'm going to close this -- its over a year old now and we got no feedback.

**Closed by gdamore** 2019-12-12 02:14 UTC
