### ISSUE TITLE
nng_recv blocked with NNG_FLAG_NONBLOCK enabled in qt gui program

### ISSUE THREAD

**Issue by tisyang** [nanomsg/nng#942] opened 2019-05-17 02:00 UTC
## NNG & Platform details.
nng version: 1.1.1

platform: debian stretch x86_64

## Expected Behavior
I have two programs:  

1. a backend program written in c to publish sensor messages from device,  using `nng_pub` protocol. I test it OK by using `nngcat` which receiving messages succesfully.

2. a frontend program written in c++ and qt, receiving messages from backend, showing on gui, using `nng_sub` protocol. The program will block in calling `nng_recv` somehow.

In qt program, socket is init in window construction(use `ipc` transport in `URL_STATUS_PUB` ):
```cpp
    int rv;
    if ((rv = nng_sub0_open(&m_nsub)) != 0) {
        LOG_ERROR("nng_sub0_open error:%s", nng_strerror(rv));
        exit(1);
    }
    nng_setopt_int(m_nsub, NNG_OPT_RECVBUF, 100);
    nng_setopt_ms(m_nsub, NNG_OPT_RECONNMINT, 1000);
    nng_setopt_ms(m_nsub, NNG_OPT_RECONNMAXT, 0);
    if ((rv = nng_dial(m_nsub, URL_STATUS_PUB, NULL, NNG_FLAG_NONBLOCK)) != 0) {
        LOG_ERROR("nng_dial error:%s", nng_strerror(rv));
        exit(1);
    }
```
calling `nng_recv` in a qt timer callback(timer interval 50ms) :
```cpp
    LOG_DEBUG("handle timeout...");
    char* buf;
    size_t sz;
    int rv = nng_recv(m_nsub, &buf, &sz, NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);
    LOG_DEBUG("nng_recv = %d", rv);
    if (rv == NNG_EAGAIN) {
        LOG_DEBUG("msg not ready");
        return;
    }
    if (rv != 0) {
        LOG_DEBUG("nng_recv failed, %s", nng_strerror(rv));
        return;
    }
    LOG_DEBUG("got msg");
```

## Actual Behavior
The qt program will block in calling `nng_recv` instantly timer triggered or a few times timer function called. The `NNG_FLAG_NONBLOCK` flag does not work somehow.

I try another way, using a thread in qt program to receive message:

```cpp
void MainWindow::status_thread()
{
    LOG_DEBUG("stauts thread...");
    char* buf;
    size_t sz;
    while (1) {
        std::this_thread::sleep_for(std::chrono::microseconds(3));
        int rv = nng_recv(m_nsub, &buf, &sz, NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);
        if (rv == NNG_EAGAIN) {
            LOG_DEBUG("msg not ready");
        } else if (rv != 0) {
            LOG_DEBUG("nng_recv failed, %s", nng_strerror(rv));
            return;
        }
        LOG_DEBUG("got msg");
        nng_free(buf, sz);
        ...
    }
    LOG_DEBUG("thread exit");
}
```
But the thread will block in calling `nng_recv` after a few loops in `while`. If I close the qt program, thread will resume from blocking and `nng_recv` return with error "Object closed".

## Steps to Reproduce
The blocking can reproduce every time I start the qt program.

I need some time to write a simple qt program to demonstrate the program.

**Comment by gdamore** [comment] 2019-05-19 22:40
There is an interesting bug in your sample loop - you wind up calling nng_free() on your bug multiple times - you should only do that if rv == 0.

**Comment by gdamore** [comment] 2019-05-19 22:43
Can you please correct the incorrect call to nng_msg_free() so that it only occurs if you actually successfully receive a message?  If the problem does not recur after doing that, I'll assume that heap corruption was to blame.  If it *does* recur, then I'll investigate further.

**Comment by tisyang** [comment] 2019-05-20 00:33
@gdamore Thanks, I will correct it and test agian.

**Comment by tisyang** [comment] 2019-05-20 00:48
correct thread loop code:
```cpp
void MainWindow::status_thread()
{
    LOG_DEBUG("stauts thread...");
    char* buf;
    size_t sz;
    while (1) {
        std::this_thread::sleep_for(std::chrono::microseconds(5));
        int rv = nng_recv(m_nsub, &buf, &sz, NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);
        if (rv == NNG_EAGAIN) {
            LOG_DEBUG("sub msg not ready");
            continue;
        }
        if (rv != 0) {
            LOG_DEBUG("recv drive status nng_recv failed, %s", nng_strerror(rv));
            return;
        }
        LOG_DEBUG("got msg");
        nng_free(buf, sz);
    }
    LOG_DEBUG("thread exit");
}
```
I test it again, the thread will still block on calling `nng_recv` when a message arrives.
```text
...
08:42:32.324 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.324 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.324 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.324 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.325 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.325 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.325 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.325 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.325 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.326 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.326 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.326 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:32.328 DEBUG mainwindow.cpp:332: sub msg not ready
08:42:33.456 DEBUG mainwindow.cpp:336: recv drive status nng_recv failed, Object closed
terminate called without an active exception
```

**Comment by gdamore** [comment] 2019-05-20 00:51
Thanks, I'll have a look.

**Comment by gdamore** [comment] 2019-05-20 00:57
Would be a bit easier if you had a simple standalone C repro case...

**Comment by tisyang** [comment] 2019-05-20 01:02
@tisyang I am writing a simple example code with qt.

**Comment by tisyang** [comment] 2019-05-20 01:31
@gdamore repo link: https://github.com/tisyang/nngqt_test
dependencies: cmake, qt5
font end qt program is in `gui` subdirectory.

**Comment by gdamore** [comment] 2019-05-20 01:46
I'm unable to reproduce with my simple program (no qt5 dependency):

```
#include <stdio.h>
#include <stdlib.h>
#include <nng/nng.h>
#include <nng/protocol/pubsub0/pub.h>
#include <nng/protocol/pubsub0/sub.h>
#include <nng/transport/ipc/ipc.h>
#include <nng/supplemental/util/platform.h>
#include <unistd.h>
#include <time.h>

nng_socket pubs;
nng_socket subs;

void subloop(void *arg)
{
	int rv;
	for (;;) {
		char *buf;
		size_t sz;
		time_t now;
		rv = nng_recv(subs, &buf, &sz, NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);

		switch (rv) {
		case NNG_EAGAIN:
			now = time(NULL);
			printf("NNG_EAGAIN %s", ctime(&now));
			break;
		case 0:
			printf("GOT message\n");
			nng_free(buf, sz);
			break;
		default:
			printf("GOT ERROR %s\n", nng_strerror(rv));
			return;
		}
		usleep(3);
	}
}

int main(int argc, char **argv)
{
	nng_thread *tid;

	if ((nng_sub0_open(&subs) != 0) ||
	    (nng_pub0_open(&pubs) != 0)) {
		exit(1);
	}


	nng_setopt_int(subs, NNG_OPT_RECVBUF, 100);
	nng_setopt_ms(subs, NNG_OPT_RECONNMINT, 1000);
	nng_setopt_ms(subs, NNG_OPT_RECONNMAXT, 0);

	nng_listen(pubs, "ipc:///tmp/ipctest", NULL, 0);
	nng_dial(subs, "ipc:///tmp/ipctest", NULL, 0);

	nng_thread_create(&tid, subloop, NULL);

	sleep(60);

	nng_close(subs);
}
```

**Comment by gdamore** [comment] 2019-05-20 01:53
So I'll need more information to debug this.  You could look at the threads with a debugger if you like.  Is there really a thread blocked in nng_recv().  If so, can you provide a backtrace.

I'd rather not have to install qt5, nor do I want to debug through that, to test your larger program.  As I said, the simple example I created above (60 lines, which you can compile on the command line easily enough if you like) seems to work without issue.

**Comment by tisyang** [comment] 2019-05-20 02:39
@gdamore console program `sub` receives OK, as `nngcat` works fine. I suspect `nng` conflict with qt libraries. If comment the `nng_recv` line, the thread print periodly.
I use `nng` to connect backend console program and frontend gui program. If nng cannot be using in gui program, it will limit it power.
Next, I try to use qt thread to rewrite the sub code, and test.

**Comment by gdamore** [comment] 2019-05-20 04:36
qt shouldn't matter... but I don't know how qt works -- the fact that C++ is also involved further complicates things.

If you can, I'd recommend avoiding using the timeout with nonblocking operations and instead using callbacks.  This may require synchronization against the main qt event loop, of course.

**Comment by tisyang** [comment] 2019-05-20 05:38
UPDATE:  I change the protocol from pub/sub to pair0, then the problem disappeared, nng_recv no longer blocks.

**Comment by gdamore** [comment] 2019-05-21 23:13
Oh, if you have no NNG_OPT_SUB_SUBSCRIBE then the messages are discarded.  Setting it to "" instead subscribes to *everything*.

This should not have made a difference.  I'll have to have a look.

**Comment by codypiersall** [comment] 2019-05-28 16:48
@gdamore I think @tisyang's problem was just that they weren't subscribed to anything—looks like there's not actually anything to take a look into, and everything is working as expected.

**Comment by gdamore** [comment] 2019-05-28 17:09
I think it's still a bug.  The lack of a subscription should not impact NNG_FLAG_NONBLOCK.

**Comment by codypiersall** [comment] 2019-05-28 17:54
Ah, got it, you are of course correct.

Turns out it non-block is only ignored whenever there is a message in the receiver's queue; may be an order of checks thing, where the code that checks for non-blocking sees there is a message, then it turns out the subscriber isn't subscribed to the topic and so doesn't return the data.

**Comment by gdamore** [comment] 2019-12-12 02:27
So I've added a test case, and I don't think master behaves this way -- I think it's fine.
I'm closing this.  Feel free to reopen if you think otherwise.  Please make sure to test against the latest code.

**Closed by gdamore** 2019-12-12 02:27 UTC
Labels: bug
