### ISSUE TITLE
TCP connections through docker-proxy do not reconnect

### ISSUE THREAD

**Issue by ScottDaniels** [nanomsg/nng#970] opened 2019-07-12 21:12 UTC
## NNG & Platform details.
NG version: Current (master) branch (pulled July 11, 2019)
Platform:  Linux 4.15.0-51-generic #55-Ubuntu
Programming language:  C
CMake options used for NNG:  -DBUILD_SHARED_LIBS=1  

Other environmental factors: Processes are running in docker containers and communicating via docker-proxy.

## Expected Behavior
When a TCP connection between two processes is broken,  NNG reconnects when the failing process restarts.  (Processes are suing NNG-Push/Pull protcol running in docker containers, and networking is via docker-proxy.)

## Actual Behavior
NNG recognises the session failure, and attempts the reconnection **only a single time;** this happens long before the second process has recovered and restarted, and no additional attempts to connect are made.

Investigation shows that after the connection to the listener is broken,  NNG makes one connect() system call which is deferred (shows in progress)  and then succeeds establishing a 'half session' with the docker-proxy (SYN and a return of SYN-ack is observed).  We also observe that the pipe negotiation callback in transport/tcp/tcp.c is invoked multiple times,  and notices an error state (before the 10s timeout); error code in the function  is driven.  After this, the connect (dialer) code is never driven to reattempt the session. 

My theory was that because the half session appears active, NNG believes that the connection is good, but some state was not properly cleaned up when the error code in the pipe nego function was driven.   

Digging a bit further, I also observed that the dialer_timer callback (core/dialer.c) was only being driven once in this situation, and noticed that the NNG_ECLOSED/NNG_ECANCELED case  in the dialer_connect_cb() fuction was being taken; the comment there is no action is needed.  However, if I reset the d->d_started flag in the dialer, and schedule the dialer timer (as is done for the NNG_ETIMEDOUT case in the same switch, that NNG will retry the session and eventually establish a new connection when the second process restarts. 

I can submit a PR for this change, however I'm not sure that this is a complete fix, thus I'll start with a bug report.

## Steps to Reproduce
1) in two containers, started such that the exposed ports are available on the docker default network, start a 'listener' in one container, and a 'sender' in the other.

2) after sender establishes a TCP connection through the proxy to the listener, and messages are being exchanged, stop the listener process

3) restart the listener process, observe that the session does not resume. 

At present, I do not have a simple example, however I could build one of that becomes necessary.

**Comment by gdamore** [comment] 2019-07-12 21:22
Sounds like we have a problem with conflating locally initiated close with a problem caused by a remote handle being closed.  We normally expect NNG_ECLOSED to mean that the local application has closed the socket, so restarting would not be appropriate.

What we need to do is use a different error code to discriminate between a remote / protocol error and the administrative local close/shutdown.

**Comment by ScottDaniels** [comment] 2019-07-15 12:11
That makes perfect sense. I wasn't thinking about application initiated close, and my hack would have caused odd problems with that.

**Comment by gdamore** [comment] 2019-07-18 03:11
So I suspect what is happening, looking at this a bit more closely (but I don't have this particular set up) is that we're trying to read, getting zero bytes back indicating that the remote side has shutdown the connection, and returning NNG_ECLOSED.  This occurs for TCP in the platform level TCP code in NNG. (See e.g. src/platform/posix/posix_tcpconn.c line 179.)

What we need to do is have a different error here, indicating that the remote side has closed it's connection, which should be distinct from the NNG_ECLOSED value we get when the connection is closed locally.

We might try to repurpose NNG_ECONNRESET for this, but I suspect a better value would be to create a new error code, say NNG_EPEERCLOSED to indicate that the peer has shut down (gracefully) it's side of the connection.

Unfortunately this will mean creating a new error code, with possible ramifications for applications.  Still its probably not too onerous to applications if we start giving back a new error code.

**Comment by gdamore** [comment] 2019-07-18 03:11
Could also use NNG_ECONNSHUT for symmetry.

**Comment by ScottDaniels** [comment] 2019-07-19 21:08
I've recreated and can confirm that `src/platform/posix/posix_tcpconn.c line 179` is indeed being driven as the reconnect attempt is happening; specifically as the negotiation is going on.   Hope that helps. 

I don't think a new error would be all that bad, but I could see making a case for reusing NNG_ECONNREST or creating   NNG_ECONNSHUT.

**Comment by gdamore** [comment] 2019-08-10 02:31
If you can try out the changes in #981 that would be helpful to me.  Once we verify it, I'll merge it in.

**Comment by gdamore** [comment] 2019-08-10 02:31
@ScottDaniels ^^

**Comment by ScottDaniels** [comment] 2019-08-12 12:10
Ack.  Away for the weekend; I will have a go this morning.

**Comment by ScottDaniels** [comment] 2019-08-12 15:18
Partially working. Comments on the pull request #981 .

**Comment by ScottDaniels** [comment] 2019-09-24 20:00
Just to update here too.... fetched the changes on the PR (#981) and have verified that the problem does NOT occur when the new code is linked into the application.     This can be closed on merge.

**Closed** 2019-09-25 01:50 UTC
