### ISSUE TITLE
Q: Does nng has 'Too many open files' quesion?

### ISSUE THREAD

**Issue by cathaysia** [nanomsg/nng#1646] opened 2023-02-21 05:12 UTC
Does nng have a "Too many open files" problem similar to zmq?

ZeroMQ opened too many file descriptors in my job and exceeded the system limit. Although I know it's possible to modify via ulimit, I don't think it's a good way to do it.

So I'll take a look at nng. I don't see similar bugs in the issues, but I hope to get further confirmation from you

**Comment by gdamore** [comment] 2023-02-21 06:03
If you open a lot of connections, it is indeed possible to blow past the limit.  If you want this level of scalability, then yes, you need to do so with ulimit.  And that is the *correct* way to do this on UNIX/Linux systems.

However, it's quite likely that if you're not using legacy notification mechanisms (i.e. you use AIO for example), then NNG may wind up using quite a few less open files than ZMQ.  ZMQ needs to open a two additional files for each *socket* (not connection), to provide for notification of events.  NNG has to do this if you use the polling file descriptor method (which might needed e.g. with some language plugins), but if you use the more efficient AIO mechanism then it doesn't do this.

No matter how you cut it, you will have (in both ZMQ and NNG) one open file descriptor per active TCP connection.  That's unavoidable, as it's how these connections work on POSIX (and even Windows) systems.

**Comment by gdamore** [comment] 2023-02-21 06:03
Closing as this is just a question, which I've answered.

**Closed by gdamore** 2023-02-21 06:03 UTC
Labels: question

**Comment by cathaysia** [comment] 2023-02-21 06:14
Thanks for your answer. In my program (14 NIC interfaces, 2 pub-sub sockets, 16 threads), zmq opens 200+ file descriptors whenever there is a sub socket connected. nng will this happen?

**Comment by gdamore** [comment] 2023-02-21 06:21
That sounds super excessive.

The issue isn't the number of NIC interfaces, but how many instances of your client you run.  Each time a new client connection is established, that will be an FD (actually 2, one for the client and one for the server).

I suspect that if you're seeing this behavior even with ZMQ that there is a logic bug in your code somewhere.  NNG will definitely not do that, unless you are constantly redialing.  (And you shouldn't do that) -- call NNG dial just once (per client), and then keep using the same socket for all your needs. :-)

**Comment by cathaysia** [comment] 2023-02-21 06:36
Yes, I don't know exactly how zeromq works. but
1. Change the listening port from "tcp://0.0.0.0:xxx" to "tcp://127.0.0.1:xxx"
2. Reduce the number of threads in zmq context
This improved my program significantly.
I don't intend to talk too much about zmq under nng. Also please understand.

Thank you very much for your answer :)
