### ISSUE TITLE
server hang waiting for client handshake

### ISSUE THREAD

**Issue by jfsmig** [nanomsg/nng#848] opened 2019-01-04 13:59 UTC
## NNG & Platform details.
I am currently working with:
* **nng** at the commit ID `37eaa558cb144fe307d7305514b58c732cb099d4` (current HEAD of the master branch) but the behavior has been reproduced with the commit ID `8a9fd805d96201c780610b765f9e6dd9f2eda642` (tag v1.1.1)
* **Linux** Fedora 28 host, kernel `4.19.10-200.fc28.x86_64`
* **gcc** `8.2.1 20181215 (Red Hat 8.2.1-6)`

## Expected Behavior
I expect a  REP0 server to continue accept connections and handle requests despite the junk from the network.

## Actual Behavior
I observe my whole minimal server is stuck after a connection that didn't respect the REQREP0 protocol. I manually connect either to an `ipc://` or a `tcp://` socket and break the client. then it seems the server doesn't manage well this event and forget to wake a thread because a failed asynchronous tasks.

## Steps to Reproduce
I wrote that minimal REP server:
```c
#include <assert.h>
#include <nng/nng.h>
#include <nng/protocol/reqrep0/rep.h>

static char buf[] = "o, World!";

int main(int argc, char **argv) {
  nng_socket sock = {0};

  int rc = nng_rep0_open(&sock);
  assert(rc == 0);
  for (int i=1; i<argc ;i++) {
    rc = nng_listen(sock, argv[i], NULL, 0);
    assert(rc == 0);
  }

  for (;;) {
    nng_msg *msg = NULL;
    rc = nng_recvmsg(sock, &msg, 0);
    if (rc == NNG_EAGAIN || rc == NNG_EINTR)
      continue;
    if (rc == NNG_ECLOSED)
      break;
    assert(rc == 0);
    rc = nng_send(sock, buf, sizeof(buf), 0);
    assert(rc == 0);
  }

  nng_close(sock);
  nng_fini();
  return 0;
}
```

I build this with the subsequent command line
```shell
gcc -g -pipe -Wall -Werror -Wextra -std=c99 -o /tmp/minimal minimal.c -lnng
```

I run the server like this:
```shell
/tmp/minimal ipc:///tmp/sock
```

I try the `nngcat` CLI tool, and it seems to work ans expected:
```shell
# time for i in 0 1 2 3 ; do nngcat --data Hell --req0 --dial ipc:///tmp/sock ; echo $?; done
0
0
0
0

real    0m0.019s
user    0m0.004s
sys     0m0.013s
```

Then I do weird junk action ... hmmm no, just connecting to the socket is enough:
```shell
# time nc -U /tmp/sock 
SP1^C
real    0m2.105s
user    0m0.016s
sys     0m0.005s
```

Then the server is stuck, when I come back on the `nngcat` tool it can not connect anymore:
```shell
# time for i in 0 1 2 3 ; do nngcat --data Hell --req0 --dial ipc:///tmp/sock ; echo $?; done
^C

real    0m3.484s
user    0m0.001s
sys     0m0.005s
```

I dumped the backtraces of each thread, with `gdb`, and it appears that all the thread are stuck in `#0  0x00007ffff73a862c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0`

I didn't investigate more yet.

**Comment by gdamore** [comment] 2019-02-18 17:37
So I believe the problem is that we wind up "attaching" the accept aio to the pipe before it is done negotiating, which leads to a surprising and unfortunate circumstance, where a poorly behaved peer can "stall" the session.

There are two things we can and should do:

1. Move the aios into their own queue, and distance them from the accept loop.  (A similar situation comes up for connect, btw.) We then need to "matchmake" oustanding aios against available open pipes.

2. We need to track progress, and use a timeout, so that pipes which take longer than say 1 second to negotiate are automatically closed.  This would provide a defense against resource consumption caused by a malicious remote end.

**Comment by gdamore** [comment] 2019-02-19 04:19
I have a draft fix for this for TCP that seems to work.  It needs a bit of polishing (the code is kind of ugly), and we will need to change the way statistics are updated for listeners.  Part of these changes will leverage knowledge that the upper layers of NNG never issue more than a single request against a dialer or listener at a time. 

The other thing is that the work I've done will have to be ported to TLS+TCP and IPC.  I don't believe that any of the other transports are impacted by this.

**Comment by gdamore** [comment] 2019-02-22 04:14
I will likely integrate a fix for this, for just TCP, to start, and follow up with fixes for IPC and TLS+TCP in separate bugs.

**Closed** 2019-02-23 20:11 UTC
Labels: bug
