### ISSUE TITLE
always see 1% message drop on listener

### ISSUE THREAD

**Issue by vikramkarandikar** [nanomsg/nng#878] opened 2019-02-15 21:40 UTC
NNG Version : 1.1.0

I  did some experiments about how much msg/sec i can pump on a Pair socket with one listener and one dialer. What i found out is irrespective of message size and number of messages per iteration i always see a message drop of around 1%

iteration | total messages      received | total time | msg/sec | drop rate
-- | -- | -- | -- | --
0 | 14927 | 1105 | 13508.60 | 0.49
1 | 14866 | 1072 | 13867.50 | 0.89
2 | 14931 | 1255 | 11897.20 | 0.46
3 | 14965 | 1252 | 11952.90 | 0.23
4 | 14983 | 1101 | 13608.50 | 0.11
5 | 14913 | 1082 | 13782.80 | 0.58
6 | 14919 | 1197 | 12463.70 | 0.54
7 | 14861 | 1067 | 13927.80 | 0.93
8 | 14931 | 1093 | 13660.60 | 0.46
9 | 14900 | 1130 | 13185.80 | 0.67

these stats are collected on listener and sent back to dialer upon request. Each iteration is attempting to send 15k messages. So if I 4k messages per iteration then receive side would give number in 1% less range. same for any number of messages i send. i thought m

**Comment by gdamore** [comment] 2019-02-16 19:16
That drop rate is not 1%, but in some cases .1%.  This is significant.

The only ways that pair should *ever* drop messages are:

1. Closing the socket (or application) before the messages have completely been sent (add a 1s delay after sending your last message to see if this is the problem.)

2. Closing the socket (or application) before the messages have *arrived*.

3. If a TCP connection is dropped or aborted for some other reason?

4. Using raw sockets (including "nng_device") it is possible for the framework to drop messages due to being overwhelmed (there is no backpressure for raw sockets)

5. Using polyamorous mode with Pairv1, a polyamorous sender can fail to deliver messages to a peer if the peer cannot accept it due to flow control or not being fully connected).  This is necessary to prevent backpressure from impacting other peers.  Note that the only peer that should be impacted by this is a slow peer.  Any receiver that can receive faster than the sender can send should be fine.

**Comment by gdamore** [comment] 2019-02-16 19:16
If you are seeing message drops in any case that is not one of those 5, it is most likely a bug.

**Comment by vikramkarandikar** [comment] 2019-02-16 19:36
the 'drop rate' column should be 'drop %', sorry about that.
0.93, 0.89 are almost 1% hence the title.

- I am not explicitly closing application/ socket/ listener/ dialer till all the iterations are complete.

- Also i would expect for any scenario in 1,2,3 , application would receive NNG_PIPE_EV_ADD_POST/ NNG_PIPE_EV_REM_POST event. I have handled these events and don't see any logs indicating such an event happened.

- There is a 2 second of wait before report is fetched from listener (which contains total time and total messages received by listener).

- Dialer never returns any error for nng_sendmsg, there is a check on nng_sendmsg and on any error (even on NNG_EAGAIN) I just stop the test. but nng_sendmsg has been always returning 0.


Do you think I should try something else? Do you want me to get any more data? Which could help analysis?

**Comment by gdamore** [comment] 2019-02-17 03:33
Yes, .93 is close to 1%.  But 0.11 is *not*.  These differences are significant enough to justify investigation.

Do you have test code you can share?  Maybe something will become evident when I look.

I'd look very closely at your "close" logic -- that's usually what hurts folks.  Closing the sender can cause message loss, even after you *think* the message is sent.  That's because the message is actually queued for delivery when control is returned to the application.  The actual transmission (and receipt by the peer) usually takes a little (perhaps a couple of milliseconds, depending on the link speed and message size) to complete in the background.

This is why I usually suggest injecting a delay of 1 second after you're done sending, *before* you close the socket (or exit the application).

Acknowledged protocols (REQ/REP) don't suffer this problem.  But all the others that have no ack as part of the low level transport can have trouble here.

Are you using polyamorous mode?

**Comment by vikramkarandikar** [comment] 2019-02-17 04:17
As i said earlier i am not closing any listener/ dialer/ socket even after test is complete.

Sender code

    for (int64_t i = 0; i < num_messages; ++i) {
        flatbuffers::FlatBufferBuilder builder(3 * 1024);
        create_message(builder);
        nng_msg *msg = nullptr;
        nng_msg_alloc(&msg, builder.GetSize());
        nng_msg_append(msg, builder.GetBufferPointer(), builder.GetSize());

        int result = 0;
        if ((result = pipe->sendmsg(msg)) != 0) {
            syslog(LOG_ERR, "message sending failed on pipe : %d, message size: %d, error : %d %s",
                   nng_pipe_id(pipe->m_nng_pipe), builder.GetSize(),
                   result, nng_strerror(result));
            ++failure;
            nng_msg_free(msg);
        } else {
            ++success;
        }
        usleep(m_sleep_time);
    }

receiver code

the call routine registered in my application libevent.

            nng_msg *msg = nullptr;
            int result = nng_recvmsg(m_nng_socket, &msg, NNG_FLAG_NONBLOCK);
            if (result != 0) {
                syslog(LOG_ERR, "uniipc::base::Socket::recvmsg error : %s",
                       nng_strerror(result));
                return;
            }
            ++m_messages_received;
            m_end = std::chrono::high_resolution_clock::now();

// keeps incrementing this counter and records time and returns once dialer requests for report.

**Comment by gdamore** [comment] 2019-02-17 18:47
Is this just a single sender and receiver?  Can I see the code you are using to set up the sockets?

**Comment by gdamore** [comment] 2019-02-17 18:49
Another idea ... that I've used for debugging similar problems.  Put a sequence counter in the messages, and look on the receiver for discontiguous sequence numbers.  That might be super helpful in determining whether the drops occur at the start of the process, the end of the process, or scattered in the middle.

I can imagine a situation where polyamorous pair mode could drop messages, or for raw sockets.  No other possible situation for pair should drop messages...

**Comment by gdamore** [comment] 2019-02-17 18:52
Oh, one other thing, that occurs to me... if you're using libevent, you need to keep reading messages until you get EAGAIN.  Because if messages arrive fast enough to be queued, you can wind up getting only a single event notification even though several messages are waiting to be read.  This is like ordinary TCP streams for example, where the handler has to keep reading until there is nothing left to read (signaled by EAGAIN, or NNG_EAGAIN in this case.)

**Comment by reqshark** [comment] 2019-02-17 18:54
@vikramkarandikar, what happens when you run the test on other socket types,

like instead of PAIR maybe PUBSUB?

**Comment by vikramkarandikar** [comment] 2019-02-18 18:26
Yes @gdamore it's a single dialer and single listener code. Unfortunately i cannot paste the entire code but i will try my best to give all the pieces 

Initialization code

    url = "tcp4://10.20.200.1:7777"

    // create pair socket, this code is same for dialer and listener
    nng_pair1_open(&m_nng_socket);
    nng_setopt_ms(m_nng_socket, NNG_OPT_RECONNMINT, 200);
    nng_setopt_ms(m_nng_socket, NNG_OPT_RECONNMAXT, 200);

    nng_setopt_int(m_nng_socket, NNG_OPT_RECVBUF, 20000);
    nng_setopt_int(m_nng_socket, NNG_OPT_SENDBUF, 8192);

    nng_setopt_int(m_nng_socket, NNG_OPT_RECVMAXSZ, 1024 * 8);

    nng_pipe_notify(m_nng_socket, NNG_PIPE_EV_ADD_POST, handle_ipc_nng_peer_connection, static_cast<void*>(this));
    nng_pipe_notify(m_nng_socket, NNG_PIPE_EV_REM_POST, handle_ipc_nng_peer_connection, static_cast<void*>(this));

    // store the eventfd that can be added to application libevent
    nng_getopt_int(m_nng_socket, NNG_OPT_RECVFD, &m_fd);
    
    
    // create listener
    nng_listener_create(&m_listener, m_socket->get_nng_socket(), url.c_str());
    nng_listener_setopt_bool(m_listener, NNG_OPT_TCP_NODELAY, true);

    int flags = NNG_FLAG_NONBLOCK;
    nng_listener_start(m_listener, flags);
    
    event_assign(&red_event, evbase(),
                 socket->get_fd(),
                 EV_READ|EV_PERSIST, &ipc::base::handle_read,
                 reinterpret_cast<void*>(socket))
    
    
    
    // create dialer
    nng_dialer_create(&m_dialer, m_socket->get_nng_socket(), url.c_str());
    nng_dialer_setopt_bool(m_dialer, NNG_OPT_TCP_NODELAY, true);

    int flags = NNG_FLAG_NONBLOCK;
    nng_dialer_start(m_dialer, flags);

    event_assign(&red_event, evbase(),
             socket->get_fd(),
             EV_READ|EV_PERSIST, &ipc::base::handle_read,
             reinterpret_cast<void*>(socket))

             
    
all the return codes have been handled and on any error application gracefully exits

    Listener -> on connection indication Send Identification message on the pipe
    Dialer -> on connection indication Send Identification message on the pipe

    Dialer -> on receiving Identification message start below logic

    Step 1: Dialer -> Start (total messages to expect which is 12000)
            Listener -> Start Ack ()
            Dialer -> spwan a thread which try to complete as many iterations as possible in 30 seconds
                for 12000 messages:
                    Dialer -> construct message using FB [ code given in earlier reply ]
                    Dialer -> start pumping 1 simple String message of 2048 bytes
                    Dialer -> usleep(5);  // usec
                sleep(2) // seconds
                Dialer -> Get Report
                Thread exists...
            Listener -> Report Ack (total messages received, total time taken)
            Dialer -> store the results in vector
            Dialer -> if elapsed time is below 30 seconds GOTO step 1

Apart from the thread that sends messages in loop all the events are handled in the application main thread that is controlled by libevent.

After the iterations calculate avg, std-dev and then dump the data on console
and keep waiting for ctrl + c or quit command on console
gracefully exit application

**Comment by vikramkarandikar** [comment] 2019-02-19 14:05
@reqshark i haven't tried other types of sockets. as of now concentrating only on Pair socket.

**Comment by vikramkarandikar** [comment] 2019-02-19 14:43
The packet loss is mostly random. Do you feel the drop remains in the end part?

Here I am trying to pump 300 messages with 10 usec sleep between sending

    missing BEGIN 
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing : 248
    missing : 249
    missing : 250
    missing : 251
    missing : 252
    missing : 253
    missing : 254
    missing : 255
    missing : 256
    missing : 257
    missing : 258
    missing : 259
    missing : 260
    missing : 261
    missing : 262
    missing : 263
    missing : 264
    missing : 265
    missing : 266
    missing : 267
    missing : 268
    missing : 269
    missing : 270
    missing : 271
    missing : 272
    missing : 273
    missing : 274
    missing : 275
    missing : 276
    missing : 277
    missing : 279
    missing : 280
    missing : 281
    missing : 282
    missing : 283
    missing : 284
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing : 89
    missing : 90
    missing : 91
    missing : 92
    missing : 94
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing : 12
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing : 158
    missing : 160
    missing : 161
    missing : 162
    missing : 166
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing : 267
    missing : 268
    missing : 269
    missing : 270
    missing : 272
    missing : 273
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing END 
    missing BEGIN 
    missing END

**Comment by gdamore** [comment] 2019-02-19 14:58
Looking at your code, I suspect the problem is somehow the link between libevent and your application.  Specifically, the file descriptors used for read notification are *not* the same as those used for write notification, and you need to repeat receive in a loop until you get NNG_EAGAIN, when you're using nonblocking reads.  (Meaning if you aren't ever getting NNG_EAGAIN, you're not doing it properly.)

I am also starting to wonder if we are discarding messages rather exerting backpressure.  Based on what I am seeing here, it looks likely. If so, that's a bug in NNG.

**Comment by vikramkarandikar** [comment] 2019-02-19 15:16
dialer and listener are running in 2 separate processes on 2 separate VMs.

For write i using (not doing non blocking write) so not registering libevent for write events
nng_sendmsg(m_nng_socket, msg, 0); 

for read drop behavior is same irrespective of blocking/ non blocking (NNG_FLAG_NONBLOCK) and never get any error from
nng_recvmsg(m_nng_socket, &msg, 0);


as you said either back pressure is not getting exerted to application or receiver is has some bug.
i also tried increasing RECVBUF to 20000, but no luck.

**Comment by vikramkarandikar** [comment] 2019-02-19 17:10
just tried a run with everything blocking, not sure how to interpret the results in terms of better or worse


iteration | total messages      received | total time (ms) | msg/sec | drop %
-- | -- | -- | -- | --
0 | 300 | 45 | 6666.67 | 0.00
1 | 300 | 50 | 6000.00 | 0.00
2 | 300 | 49 | 6122.45 | 0.00
3 | 300 | 57 | 5263.16 | 0.00
4 | 300 | 50 | 6000.00 | 0.00
5 | 300 | 59 | 5084.75 | 0.00
6 | 300 | 53 | 5660.38 | 0.00
7 | 292 | 50 | 5840.00 | 2.67
8 | 295 | 47 | 6276.60 | 1.67
9 | 300 | 55 | 5454.55 | 0.00
10 | 293 | 30 | 9766.67 | 2.33
11 | 282 | 58 | 4862.07 | 6.00
12 | 300 | 54 | 5555.56 | 0.00
13 | 300 | 50 | 6000.00 | 0.00
14 | 300 | 50 | 6000.00 | 0.00
15 | 296 | 24 | 12333.30 | 1.33

**Comment by gdamore** [comment] 2019-02-19 17:34
If you're using an event loop and only doing a single operation, it doesn't matter blocking or not.  With a blocking operation it would be "unnatural" to tie into libevent.  (Blocking would normally just be a while loop that kept doing receives.)

I'm convinced that the right solution here for you is non-blocking, but to keep trying to receive until you get NNG_EAGAIN.

**Comment by vikramkarandikar** [comment] 2019-02-19 17:59
is this the correct way to implement recv part?

    void ipc::base::Socket::recvmsg()
    {
        int flags = NNG_FLAG_NONBLOCK;
        int msg_read = 0;
        while (true) {
            nng_msg *msg = nullptr;
            int result = nng_recvmsg(m_nng_socket, &msg, flags);
            if (result != 0) {
                if (result != NNG_EAGAIN) {
                    syslog(LOG_ERR, "ipc::base::Socket::recvmsg error : %s",
                           nng_strerror(result));
                }
                return;
            }

            ++msg_read;
            if (nng_msg_len(msg) < 1) {
                syslog(LOG_ERR, "received zero length msg, strange!");
                return;
            }

            nng_pipe pipe = nng_msg_get_pipe(msg);
            auto sock_eps = get_endpoint(pipe);
            if (std::get<0>(sock_eps) == nullptr) {
                syslog(LOG_ERR, "endpoint is null for socket : %s",
                       get_name().c_str());
                return;
            }

            if (std::get<1>(sock_eps) == nullptr) {
                syslog(LOG_ERR, "pipe not found for socket : %s, pipe-id : %d",
                       get_name().c_str(), nng_pipe_id(pipe));
                return;
            }

           ipc::base::Endpoint *ep = nullptr;
            ipc::base::Pipe *p = nullptr;

            std::tie(ep, p) = sock_eps;
            ep->handle_recvmsg(p, msg);

        }
        syslog(LOG_ERR, "ipc::base::Socket::recvmsg messages read : %d", msg_read);
    }

because I do see that this loop reads multiple messages on one libevent read event to application, but still the drop % is same.

**Comment by gdamore** [comment] 2019-02-19 18:03
Yes, that looks better.  I need to investigate the actual drops though -- I suspect that we're dropping instead of exerting flow control.

**Comment by vikramkarandikar** [comment] 2019-02-19 21:03
One more input, I also tried a timer based approach, where I am scheduling a 5 ms timer in application libevent. On expiry invoking above method and still same amount of drop %.

This eliminates a case where application failed to read all the messages on libevent read event and messages are left in the socket buffers. 

As you said this looks to be a sender back pressure issue which is dropping messages silently.

**Comment by gdamore** [comment] 2019-02-19 21:13
You shouldn't need the timer.  If you do, that would indicate a bug in either the NNG logic for the event file descriptor, or the libevent logic itself.  Having said this, NNG's event file descriptors are level triggered.  (Which in theory means that maybe my comments about EAGAIN aren't actually strictly necessary.  I forgot about the level triggering -- I'm just so used to using edge triggered stuff in other places...)

I will see if I can find some time to write a test case to reproduce the problem you're seeing, or at least identify whether backpressure is an issue.  It might be a couple of days before I get to it.

(I did do some basic review of the code, and I don't think I see any situation where this could occur -- *unless* you're using polyamorous mode.  I don't see you setting that in any of your code?)

**Comment by vikramkarandikar** [comment] 2019-02-19 21:20
i am using polyamorous mode.

nng_setopt_bool(m_nng_socket, NNG_OPT_PAIR1_POLY, true);

**Comment by gdamore** [comment] 2019-02-19 22:43
Oh, well that's the problem right there then.  Definitely, with polyamorous mode we will discard messages if the receiver cannot keep.  This is necessary in because the only other two options are:

1. Allow the message queue to grow indefinitely (possibly consuming all available system memory!)
2. Stall the sender entirely, preventing new messages from being delivered to *any* receiver until the slow receiver has caught up.

This is a general problem for *any* protocol that fans out messages from a single to source to multiple (even just one at a time) destinations.

There is a corollary here, which is that polyamorous mode is not something you want to use for benchmarking, or for pushing as hard as you can, at least if reliable delivery is something you need.

Ultimately this is the "myth" of reliable multicast.

**Comment by vikramkarandikar** [comment] 2019-02-19 23:58
Got it! after removing polymorous setting i got the ZERO drop!


iteration | total messages      received | total time (ms) | msg/sec | drop %
-- | -- | -- | -- | --
0 | 15000 | 812 | 18473 | 0
1 | 15000 | 700 | 21429 | 0
2 | 15000 | 657 | 22831 | 0
3 | 15000 | 658 | 22796 | 0
4 | 15000 | 721 | 20804 | 0
5 | 15000 | 682 | 21994 | 0
6 | 15000 | 678 | 22124 | 0
7 | 15000 | 735 | 20408 | 0
8 | 15000 | 817 | 18360 | 0
9 | 15000 | 796 | 18844 | 0
10 | 15000 | 656 | 22866 | 0
11 | 15000 | 635 | 23622 | 0

A question now...

The documentation for NNG_OPT_RECVBUF doesn't give any upper bound (NNG_OPT_SENDBUF has 8192). Now I have set NNG_OPT_RECVBUF to 20000 why do I get message drop then (Because i am pretty sure that receiver is able to accept 15000/sec based on above results)?.

So anything below this number we ideally should not see a message drop in polymorous mode with buffer size of 20000.

**Comment by gdamore** [comment] 2019-02-20 00:00
Not all protocols support the receive buffer.  It turns out actually that the drop occurs not on the receive side in this case, but on the *send* side, so its the NNG_OPT_SENDBUF that you care about.

**Comment by vikramkarandikar** [comment] 2019-02-20 00:11
Okay. So we still need to see in polymorous mode why sender doesn’t get back pressure and silently discards messages. 

Apart from this i think my query has been answered and if I want somewhat reliability i should use non polymorous mode pair socket. 

thank you for your time and quick responses.

**Comment by gdamore** [comment] 2019-02-20 02:26
The silent discard of the messages is by design with polyamorous mode.  As I already indicated, the other two options (unlimited queueing or stalling the sender altogether) are just unacceptable.

Generally speaking polyamorous mode won't drop messages unless you send them faster than the receiver can consume them.  So that does probably create some limitations on it's use.

Closing this as there is nothing further I can do at this point.

**Closed by gdamore** 2019-02-20 02:26 UTC
