### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by liamstask** [nanomsg/nng#107] opened 2017-10-08 04:21 UTC
Have been reading through nng a bit and it looks great - nice work! I have a couple general questions (hope it's OK to batch these in a single issue):
* I haven't found an api to write 'multi-part' messages - i'd like to transmit capn proto messages via nng, which are organized in memory as a collection of non-contiguous chunks, depending on the size of the message. a way to specify multiple iovec pointers would work, for example. any suggestions on how to approach this? (fallback is to copy them all into contiguous memory prior to transmit, which would be a little sad)
* would you be open to the creation of a UDP transport? not urgent, but several of the cases i'm interested in would benefit from the ability to send unreliable datagrams
* not really a question, but looking forward to either the introduction of a poller api (eventually backed by platform specific polling mechanisms) or whatever other api you introduce for similar functionality. using `poll()` is no prob in the interim, but this seems like one of the main remaining points of potential missing/unstable api.

**Comment by gdamore** [comment] 2017-10-09 17:01
Well, it does turn out that under the hood we do have iovecs, but we don't give consumers access to them.  The underlying transports have inconsistent support for multipart messages.  I will need to think about ways to express that in terms of API.

There is a draft RFC for UDP, and I want to improve it.  The problem is that when your messages exceed the size of the UDP MTU; that means we either have to accept a small message size (64K max) as a limit, or we have to do our own reassembly.  I've got primitive reassembly for an unreliable transport already implemented -- check the ZeroTier transport (the documentation for the transport is in the directory with the transport) -- and I am planning to make the UDP transport "real" at some point.

As to the "poller" API, what I plan to do is make the AIOs exposed to userland applications.  This will give applications the chance to have a callback applied on completion of I/O events.  Think Windows callbacks or IOCPs and you get the picture.

**Comment by liamstask** [comment] 2017-10-10 05:12
> under the hood we do have iovecs

right, i did see that. my primary goal at the moment is zero-copy/scatter gather i/o, though perhaps a multi-part message api would be one way to accommodate that.

> a draft RFC for UDP

great! is there a link available? i honestly think dealing w a 64k message size limit for a UDP would be acceptable, perhaps even preferable, to avoid any additional complexity and adhere to the behavior of standard UDP. as you mention, there are other options available if that is not sufficient for a given task.

> make the AIOs exposed to userland applications

does this imply that this AIO api would be backed by platform specific/higher performance polling mechanisms (i hope so)? i didn't immediately see where this might be handled in the existing AIO api, but i haven't investigated closely. i suppose i'll just need to see what you come up with 😄

**Comment by gdamore** [comment] 2017-10-13 03:03
The underlying polling mechanism is designed to be platform specific... on Windows we use IOCP.  Right now I'm using poll everywhere for POSIX and family, but that's only because I've not gotten around to writing epoll, kqueue, and dev/poll implementations yet.

**Comment by reqshark** [comment] 2017-10-25 12:26
> i honestly think dealing w a 64k message size limit for a UDP would be acceptable

in practice 64K max size for UDP is highly unrealistic.

try to use that size outside your local router and those packets immediately dropped.

Shouldn't we set default to something realistic based on what works for UDP in practice, like 4K?

**Comment by gdamore** [comment] 2017-11-06 06:03
There are cases where UDP is used *inside* the local network; having large limits can still work there.

That said, the reason for the limits are either "intrinsic" limitations in the protocols, or "security" (DDoS avoidance).  There is no reason to set a default that prevents a reasonable internal use case.

Applications which want to push data over the Internet at large should understand that if they send large messages over a lossy transport, those messages are likely to get lost.  It's not my job to replace all rational thought on the part of the developer.

**Comment by gdamore** [comment] 2017-12-27 00:25
This is not an "issue" -- meaning no code requests to change.  Closing it.

**Closed by gdamore** 2017-12-27 00:25 UTC
Labels: question
