### ISSUE TITLE
Duplicate receipts of messages this.sock.on(data)

### ISSUE THREAD

**Issue by DrYSG** [nanomsg/nng#797] opened 2018-10-09 15:49 UTC
This is very odd. I have a C++ program using  nng Nanomsg (wire protocol is identical to nanomsg). 
https://github.com/nanomsg/nng

I have a simple test harness (client.exe and server.exe) using the CPP interface and I only see one copy of a message (sent in over bus protocol). However with this JS package I am getting two copies of each message sent (cpp -> JS node program).

Node Version: 10.9.0
nanomsg: 4.0.2

This means that I get two calls to the receive() callback for each packet that arrives.

Here is my nanomsg receiver

```

const nano = require('nanomsg')
const { Topics } = require('./Payloads/Packet')

class LMB {
    constructor(config) {
        this.sock
        this.config = config
        this.nodeName = config.nodeName
        this.topicList = config.topicList
        this.topics = Topics
    }

    connect() {
        this.sock = nano.socket('bus')
        this.sock.bind(this.config.urlList[0])
        this.sock.connect(this.config.urlList[1])
        this.sock.on('data', this.receive.bind(this))
    }

    send(topic, payload) {
        let size = payload.length
        let packet = new ArrayBuffer(size + 8)
        let buffer = new Uint8Array(packet)
        let view = new DataView(packet)
        view.setUint32(0, topic, true)
        view.setUint32(4, size, true)
        buffer.set(payload, 8)
        this.sock.send(buffer)
    }

    receive(packet) {
        let view = new DataView(packet.buffer)
        let topic = view.getUint32(0, true)
        let size = view.getUint32(4, true)
        let payload = packet.slice(8, packet.length - 1)
        global.Dispatcher.process(topic, size, payload)
    }
}

module.exports = { LMB }
```

and here is the config that it uses, and the two copies of the start message that appear. I confirmed with the VSCODE debugger via breakpoints and the receive() method is being called twice for each arrival of a packet over the network.

```
C:\Program Files\nodejs\node.exe --inspect-brk=48723 orch.js 
Debugger listening on ws://127.0.0.1:48723/a3bc5322-9c99-4c22-b1fb-f053bb8d144f

For help, see: https://nodejs.org/en/docs/inspector

Orcestrator config: 
{
    "nodeName": "YSG4206-Orchestrator",
    "urlList": [
        "tcp://127.0.0.1:2019",
        "tcp://127.0.0.1:2018"
    ],
    "topicList": [
        "sim.Actor.State.Test"
    ]
}
Waiting for messages..
{
    "topic": 6,
    "size": 144,
    "topicString": "scenario.Ready",
    "source": "AFSIM-YSG-Server",
    "systemTime": {
        "low": -433850073,
        "high": 30695395
    },
    "systemTimeString": "Tue Oct  9 11:22:32 2018",
    "description": "AFSIM Ready"
}
******* starting ******
{
    "topic": 6,
    "size": 144,
    "topicString": "scenario.Ready",
    "source": "AFSIM-YSG-Server",
    "systemTime": {
        "low": -433850073,
        "high": 30695395
    },
    "systemTimeString": "Tue Oct  9 11:22:32 2018",
    "description": "AFSIM Ready"
}
******* starting ******

```

**Comment by gdamore** [comment] 2018-11-22 16:38
So I'm looking again at this:

One side must do bind.  The other side (all of them?) must do connect.  However, you need to understand how bus works.  if you have multiple parties, you probably want to configure this in a star  topology, where the central node does bind, all others do connect.  And, this means that the middle (server) node sees all messages from every other node, but the other (client) nodes will only see messages sent by the server.

Mangos (not NNG) has a pattern called STAR that extends this so that every node is actually a repeater, which is an adaptation from bus.  Unfortunately, this pattern is not part of NNG (yet).  I had plans to incorporate it.

At any rate, I'm convinced that the issue here is just confusion about how to plumb the underlying connections, perhaps combined with an insufficient understanding of bus itself.

I'm leaving this open for you to provide feedback on, but I really don't think there is more that I can do at this point.

**Comment by DrYSG** [comment] 2018-11-26 16:48
Well I worked at GTE labs 30 years ago, so we know all about STAR verus bus. But they are really two different topologies. For the work we do, dynamic join/exit via a peer peer bus is the better topology and it is a compromise to force things to a star topology.

**Comment by gdamore** [comment] 2018-11-26 17:44
On Nov 26, 2018, 8:48 AM -0800, Dr. YSG <notifications@github.com>, wrote:
> Well I worked at GTE labs 30 years ago, so we know all about STAR verus bus. But they are really two different topologies. For the work we do, dynamic join/exit via a peer peer bus is the better topology and it is a compromise to force things to a star topology.

So part of the problem is that there is an impedance mismatch in understanding how the TCP connections (or whatever) are established, and the details of how messages are forwarded *after* those connections are established.

It sounds like you want to have a true broadcast.   That means building a fully connected mesh in NNG, *or* using the STAR topology in mangos.  (STAR is an unfortunate misnomer… my bad there.  It’s an experimental protocol, but it works by having every node rebroadcast every message except to the peer it got the message from.  The bad news is that it doesn’t deal well with cycles, which is why I called it STAR.  The topology doesn’t need to be a real star network, just needs to be free of cycles.  There is some protection in there in the form of a TTL, but you still don’t want to have cycles or you will have message duplication.)

To *truly* prevent cycles, we should have used a unique ID on every message, and required systems to keep track of seen messages and discard duplicates (along with some kind of tunable timer I guess.)   Maybe someday I’ll go ahead and write that as a protocol.  A true broadcast protocol.

  - Garrett

**Comment by gdamore** [comment] 2018-12-16 19:03
I'm going to close this, since it seems to be kind of dead, and just a correction to user expectations rather than an actual bug per se.

**Closed by gdamore** 2018-12-16 19:03 UTC
Labels: feedback
