### ISSUE TITLE
Closing rep socket triggered reqRecv callback and program crashed 

### ISSUE THREAD

**Issue by cr-galrosen** [nanomsg/nng#1204] opened 2020-02-20 15:08 UTC
NNG & Platform details. 

NNG version: 1.2.5
OS: Mac
C++

## Expected Behavior

Base on the nng_listener_close documentation "Listeners are implicitly closed when the socket they are associated with is closed."
I did not expect the callback to triggered since I did not send any message.

## Actual Behavior

callback triggered and some of the allocations was already free, like nng_aio, the recv callback tried to access aio object and boom.

## Steps to Reproduce

Client side:
1. Open rep socket.
2. nng_ctx_open and nng_aio_alloc with recv callback.
3. nng_ctx_recv - wait for messages.
4. nag_listen on the rep socket.

Server side:
1. Open rep socket.
2. nng_ctx_open and nng_aio_alloc with recv callback.
3. nag_listen on the rep socket.

On shutdown in my destructor I close both client and server rep sockets.
Even when trying to go down more clean by freeing the aio object and closing the listener and then closing the socket, still triggered the recv callback and boom.

**Comment by gdamore** [comment] 2020-02-24 01:11
I think this is a problem of confusion on your part.

The callbacks are *always* called, and it's a programming error to free resources used by a callback while the callbacks are outstanding.

In this case the callback is called with an nng_aio_result() of NNG_ECLOSED.  This is how the application gets to know about the socket closing out from underneath it.

I won't be changing any code in NNG -- this is working as designed.

**Closed by gdamore** 2020-02-24 01:11 UTC

**Comment by gdamore** [comment] 2020-02-24 01:14
Actually there is one exception to the above:  nng_aio_free() may return without executing the callback.  I don't recommend relying on this though.  (It only does that if the callback hasn't started yet, and if it is successfully able to cancel the operation, which is not always guaranteed to be possible.)

**Comment by cr-galrosen** [comment] 2020-02-24 06:19
Trying to free things was a second chance to avoid the callback, at the
beginning I just closed the socket at the destructor of my class.
I hope you are right, I will give it a try and let you know, because I
remember case were nng_aio_result return 0 but then the message was null.

I am doing this cleanup because I am running tests using gtest and I
noticed that if I am not closing the socket, then the next gtest test try
to listen on the same address and fails with address in use.


בתאריך יום ב׳, 24 בפבר׳ 2020, 03:14, מאת gdamore ‏<notifications@github.com

**Comment by gdamore** [comment] 2020-02-24 13:39
So for your use case, the correct way to handle this is:

nng_close() the socket
nng_aio_wait() for each outstanding aio that was using the socket (they will probably all get NNG_ECLOSED)
teardown the resources (you can use nng_aio_free at this point.)

**Comment by cr-galrosen** [comment] 2020-02-24 16:36
Hi,
I am not sure it will work since calling nng_close at the destructor will
trigger the callback, at that point the destructor already free the
resources, so I cannot call to nng_aio_result.
Gal.

בתאריך יום ב׳, 24 בפבר׳ 2020, 15:39, מאת gdamore ‏<notifications@github.com

**Comment by gdamore** [comment] 2020-02-24 19:18
So somehow whatever you are doing to link your teardown needs to happen first.  I'm not sure about how you've organized your stuff, but I thought C++ didn't actually *destroy* the object until *after* the destructor returned.

This means that if you call nng_aio_wait() in your destructor immediately after calling nng_aio_close, you should be ok.

That said, this may cause the destructor to block.  Whether that represents a problem for your  code base is something that only you can resolve -- it depends entirely on your code.

The alternative would be for you to figure out how to keep a reference to the object being destroyed alive until after the callbacks associated with it are released.  One possible way to do that would be to reference count them -- incrementing the reference before submitting the callback, and decrementing it in the callback, and only calling "free" if the reference count drops to zero.  I'm not a C++ wizard, but I seem to recall C++ has some new-fangled way to reference count pointers as well -- maybe that can help?

My position on these callbacks stands -- the callbacks still execute on nng_close().  A lot of code out there relies upon this behavior, and it is how I intended.
