### ISSUE TITLE
NNG_OPT_SUB_SUBSCRIBE

### ISSUE THREAD

**Issue by u32744** [nanomsg/nng#1920] opened 2024-11-07 00:38 UTC
**Describe the bug**
gcc pubsub.c -lnng -o pubsub
pubsub.c: In function ‘client’:
pubsub.c:63:19: warning: implicit declaration of function ‘nng_setopt’; did you mean ‘nng_send’? [-Wimplicit-function-declaration]
         if ((rv = nng_setopt(sock, NNG_OPT_SUB_SUBSCRIBE, "", 0)) != 0) {
                   ^~~~~~~~~~
                   nng_send
pubsub.c:63:36: error: ‘NNG_OPT_SUB_SUBSCRIBE’ undeclared (first use in this function); did you mean ‘NNG_OPT_SUB_PREFNEW’?
         if ((rv = nng_setopt(sock, NNG_OPT_SUB_SUBSCRIBE, "", 0)) != 0) {
                                    ^~~~~~~~~~~~~~~~~~~~~
                                    NNG_OPT_SUB_PREFNEW
pubsub.c:63:36: note: each undeclared identifier is reported only once for each function it appears in

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NNG version:  latest
 - Operating system and version: windows
 - Compiler and language used:  cmake
 - Shared or static library

**Additional context**
NNG_OPT_SUB_SUBSCRIBE

**Comment by gdamore** [comment] 2024-11-08 06:17
The API for the "main" (or development) branch has changed.  The "stable" branch (1.9.0 is the latest) has the old API still.

https://github.com/nanomsg/nng/tree/stable

For details on the API changes -- and there are more coming -- you can see 

https://github.com/nanomsg/nng/blob/main/docs/ref/migrate/nng1.md

In this particular case, instead of using `NNG_OPT_SUB_SUBSCRIBE` as an option, you should instead use the first class function:

`nng_sub0_socket_subscribe` (or for contexts, `nng_sub0_ctx_subscribe`)

There is a similar pair of functions for unsubscribing.

**Comment by gdamore** [comment] 2024-11-08 06:18
I'm closing this because it's not a bug, it's a known breaking API change (the "main" branch will be "2.0" eventually, a new major version with breaking changes like this).

**Closed by gdamore** 2024-11-08 06:18 UTC
