### ISSUE TITLE
Test failures due to Unrecognized command line option '-t'

### ISSUE THREAD

**Issue by barracuda156** [nanomsg/nng#1647] opened 2023-03-05 07:16 UTC
Multiple tests fail due to usage of unsupported flag `-t`:

```
1/81 Testing: nng.core.aio_test
1/81 Test: nng.core.aio_test
Command: "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_nng/nng/work/build/src/core/aio_test" "-t" "-v"
Directory: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_nng/nng/work/build/src/core
"nng.core.aio_test" start time: Mar 05 15:11 CST
Output:
----------------------------------------------------------
Unrecognized command line option '-t'.
Try '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_nng/nng/work/build/src/core/aio_test --help' for more information.
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"nng.core.aio_test" end time: Mar 05 15:11 CST
"nng.core.aio_test" time elapsed: 00:00:00
```

This is on 10.6.8 and with `gcc-4.2`; however, documentation says C99 is used, therefore `gcc-4.2` should work.

**Comment by barracuda156** [comment] 2023-03-05 07:46
UPD. Well, it fails with `gcc-12.2.0` as well, so the issue is not caused by an outdated GCC.

**Comment by barracuda156** [comment] 2023-03-05 08:14
Apparently  it simply does not exist: https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html#Option-Summary

**Comment by gdamore** [comment] 2023-03-20 00:39
I don't think we're passing -t to gcc.

Rather this looks like a CMake / CTest problem?

Can you describe how you configured this?  What version of CMake are you using?  How did you execute these tests?

**Comment by gdamore** [comment] 2023-03-20 00:40
Ah, this looks like the code from cmake/NNGHelpers.cmake -- that -t is not appropriate anymore.

**Comment by gdamore** [comment] 2023-03-20 00:42
I think I missed this because these days I run all my tests using Ninja, and somehow this is overlooked.

**Comment by gdamore** [comment] 2023-03-20 00:43
Wait... -t -v works for me.

**Comment by gdamore** [comment] 2023-03-20 00:50
Aha!

The problem is your environment lacks POSIX timekeeping, and is not Windows.

Building for Snow Leopard is the root of the problem.  I could fix this if I was really so inclined -- by removing the -t (which isn't strictly necessary but it does give us some help during the test runs -- I like to see the timing in test runs), but honestly the net benefits here fall far short of the functionality I'd lose.  I'm simply not very interested in supporting such an old version of macOS.

I don't have a system that will run it, and I don't have easy access to a copy of Snow Leopard even if I did.

Sorry... I highly recommend moving to something that isn't 15 years old.

**Comment by gdamore** [comment] 2023-03-20 00:51
Newer versions of macOS closed many of the core problems with timekeeping and synchronization (Pthreads are abysmal on older versions of Darwin, as they are "fair share" and you have to take a context switch even when acquiring or releasing an uncontended mutex.)

**Closed by gdamore** 2023-03-20 00:51 UTC

**Comment by barracuda156** [comment] 2023-03-20 07:32
@gdamore Thank you for detailed reply. Just to be sure, it works with GCC being the compiler, not Clang?
`-time` is supported on 10.5 and 10.6, if it is the same, I can get time stats when building on it.

P.S. It is impossible to run anything newer than 10.6 on PowerPC machines, since, sadly, Apple dropped the arch support in some of the mid-way builds of 10.6 and completely removed PPC code in 10.7.
