### ISSUE TITLE
Possible to retrieve the port used for WebSocket

### ISSUE THREAD

**Issue by jonthn** [nanomsg/nng#830] opened 2018-12-28 09:29 UTC
## NNG & Platform details.

NNG 1.1.1  - Platform : macOS

## Wish

I would like to use an url of this form : `ws://*:0/foobar` in order to start listening to a random available port of the system. 
This works but how do I "discover" / obtain the port it's currently listening too ?
With transport `tcp://` it works as expected but it doesn't with `ws://`

I tried to use

```
nng_listener_getopt_sockaddr(listener, NNG_OPT_LOCADDR, &sock_addr);
```

but it returns `NNG_ENOTSUP` (9)

**Comment by gdamore** [comment] 2018-12-29 05:15
Yes, we should add this capability.  That's not done yet.  I presume mostly you just need the port, right?

**Comment by gdamore** [comment] 2018-12-30 19:56
Note that the incoming connections do support this today with the NNG_OPT_LOCADDR option on the underlying pipe.  This isn't precisely what you need I think, but it might help.  (What you need is to have the same option on the listener.  That's coming very soon; I'm in the middle of refactoring a bunch of the option handling to better support polymorphism and pass down options from ws to the underlying TCP and/or HTTP handlers.

**Comment by jonthn** [comment] 2018-12-30 23:15
Exactly I only need the port number as you said, and on the listener.
OK, thank you. Then I will wait for this refactoring to change my code and I will put an hard-coded number in the meantime for this test code, it should work

**Comment by gdamore** [comment] 2019-02-17 18:39
This should be fixed in master as of last night.

**Comment by gdamore** [comment] 2019-02-18 06:10
I've confirmed that this works now.  As part of #882 there is a test suite that verifies this with a port 0 binding.

You might also look at the brand-new option, NNG_OPT_TCP_BOUND_PORT, which is intended to make this even easier than NNG_OPT_LOCADDR.  (Especially in the face of both IPv6 and IPv4 binding.)

**Closed by gdamore** 2019-02-18 06:10 UTC
