### ISSUE TITLE
httpclient test failed!

### ISSUE THREAD

**Issue by afshin2003** [nanomsg/nng#787] opened 2018-11-11 14:19 UTC
## NNG & Platform details.
nng: 1.1.0
debian jessie: 8.11
GNU: 4.9.2

## Expected Behavior
All tests pass

## Actual Behavior
Total Test time (real) = 138.88 sec

The following tests FAILED:
          7 - httpclient (Failed)
Errors while running CTest
ninja: build stopped: subcommand failed.

## Steps to Reproduce
ninja test

**Comment by gdamore** [comment] 2018-11-11 15:05
The httpclient test hits a few internet servers and if they are down it
will fail.

Please run the httpclient test again separately with -v so we can see which
particular test case is failing.

  - Garrett

**Comment by afshin2003** [comment] 2018-11-12 06:40
Would you tell me how I can run it separately?

**Comment by gdamore** [comment] 2018-11-19 17:56
Well, that depends on how you built your stuff.

With ninja, there is an executable in your build tree called "tests/httpclient" (or httpclient.exe on Windows).  You can just run `tests/httpclient -v` and normally that is sufficient to test it.

**Comment by gdamore** [comment] 2018-11-19 17:56
Btw, I just ran it in my build and it is fine.

**Comment by gdamore** [comment] 2018-11-22 03:15
We are using Ubuntu 16.04 (which I think is probably newer than Debian Jessie) in our CI environment, and not seeing this issue.

One thing that occurs to me is that a proxy in the middle could change all this.  Are you sitting behind a web proxy?  The test unfortunate uses a web resource that might not be very reliable:

http://anglesharp.azurewebsites.net/Chunked

Are you able to access that site?

**Comment by gdamore** [comment] 2018-12-16 19:16
I'm closing this as not reproducible... it works for me.  The remote chunked server is kind of slow, and probably we should build a test that doesn't depend on remote services, but that's a task for a future date.

**Closed by gdamore** 2018-12-16 19:16 UTC
Labels: feedback
