### ISSUE TITLE
Request Ipc Socket not receiving any requests after trying to bind to the same socket a second time.

### ISSUE THREAD

**Issue by nagua** [nanomsg/nng#1446] opened 2021-04-15 20:52 UTC
**Describe the bug**
I copied and compiled the request response example from the nng getting started guide.
I started a node0 server and ran the client and everything worked fine.

I accidentally run the command to start the node0 server again. As it should, it failed
with address already in use. But starting the node1 client again the server wasn't responding
to requests anymore.

**Expected behavior**
The node0 server should respond to requests.

**Actual Behavior**
The client was stuck and waited for an answer.

**To Reproduce**
If possible include actual reproduction test code here.
I was using the code from this example: https://nanomsg.org/gettingstarted/nng/reqrep.html

To make the code compile I needed to cast `DATE` in line 76:

```cpp
const_cast<void*>(static_cast<const void*>(DATA))
```

** Environment Details **
 - NNG version: 1.4.0 compiled through vcpkg
 - Operating system and version
   - Ubuntu 20.04
 - Compiler and language used
   - Used g++ version 9.3.0
 - Shared or static library
   - vcpkg is using static libraries with linux

**Additional context**
Nothing to add.

**Comment by nagua** [comment] 2021-04-16 08:28
So I just tested this with `libnanomsg` and there it works as expected. So this is a nng issue, but I don't know if this is a regression with the new version or if it was already present in older versions.

**Comment by gdamore** [comment] 2021-06-02 15:28
so the examples were written for C, not C++, which is why you had problems with the compile.

I will investigate and get back to you.

**Comment by gdamore** [comment] 2021-06-02 15:33
I think something else must be wrong in your environment.  I've tested and cannot reproduce your problem.  Are you sure there are not other errors present?

**Comment by nagua** [comment] 2021-06-04 23:33
> 
> 
> so the examples were written for C, not C++, which is why you had problems with the compile.
> 
> I will investigate and get back to you.

I just might be nice to include a c-style `(void*)` cast here such that is will also easily compile with a c++ compiler.



> 
> 
> I think something else must be wrong in your environment. I've tested and cannot reproduce your problem. Are you sure there are not other errors present?

I used `nng` from `vcpkg` in a ubuntu 20.04 virtualbox vm. With `vcpkg` I do static linking of the library. Otherwise I can't think of any strange system configuration.
Do you have a pointer for me where I could start debug this on my machine to solve this mystery?

**Comment by gdamore** [comment] 2021-07-06 22:09
I don't have any specific advice, but generally I'd look at the usage of the IPC socket files themselves -- restarting the server should cause the server to recreate the socket.  (Its entirely possible that clients will fail to connect when the server isn't run, but they should reconnect later.)

If you can create a shell script around the executable programs that simulates the behavior, that might help.

**Comment by gdamore** [comment] 2021-10-17 07:12
This was actually bug #1518 I think.  It should be fixed in master now.

**Closed by gdamore** 2021-10-17 07:12 UTC
Labels: feedback
