### ISSUE TITLE
reqrep demo does not work under QNX

### ISSUE THREAD

**Issue by mbush00** [nanomsg/nng#602] opened 2018-07-18 20:51 UTC
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

NNG Version: Branch 1.0.1
Target Platform: QNX 6.5.0SP1 armv7le

I've updated cmake to allow nng to build on QNX, however when I run the provided reqrep demo code it will work once and then the server will not accept new connections.

If I run the same code on my windows box I can rerun the client indefinitely and the result is the same.

## Expected Behavior

I expect the client to display the received date every time the program is executed.

## Actual Behavior

What happens is it will work the first time, and then the second time I run the client I see 

CLIENT: SENDING DATE REQUEST

and the client is now halted until I terminate the program.

Nothing is received on the server.

I did dig a bit to see what is going on, and from what I can tell is when the client sends its second message I see that on the server in nni_posix_pipedesc_doread() [posix_pipedesc.c] the following code block is hit:

if (n == 0) {
	// No bytes indicates a closed descriptor.
	printf("nni_posix_pipedesc_doread4: ECLOSED\r\n");
	nni_posix_pipedesc_finish(aio, NNG_ECLOSED);
	nni_posix_pipedesc_doclose(pd);
	return;
}

## Steps to Reproduce

on my QNX box I run the server with:
  ./reqrep server tcp4://192.168.8.111:8899

on my windows box I run the client with 
  reqrep client tcp4://192.168.8.111:8899

the first time running the client I see the following on the server:

SERVER: RECEIVED DATE REQUEST
SERVER: SENDING DATE: Wed Jul 18 13:12:48 2018

and on the client:

CLIENT: SENDING DATE REQUEST
CLIENT: RECEIVED DATE: Wed Jul 18 13:12:48 2018

When I rerun the client I see: 

CLIENT: SENDING DATE REQUEST

and nothing on the server.

**Comment by gdamore** [comment] 2018-07-18 23:07
Ok, so I've never tested QNX with this stuff myself (last time I looked the QNX stuff wasn't free or easy for open source devs to get a hold of).  Receiving an empty message is supposed to indicate a closed file, but maybe QNX differs somewhat here?

Also, I've changed the cleanup/teardown somewhat, so if you have time to do so, maybe you can test master?

**Comment by mbush00** [comment] 2018-07-19 12:45
Did a sync to d4d49cef92356778215c757e8f6d1d0d35662a64

Retried my test, the result is the same.

As another test I modified the client to iterate multiple requests and that seems to work as expected.

I wonder as well if QNX is differing slightly, as the call to getaddrinfo() in posix_resolv_gai.c was failing because hints.ai_socktype is 0, which the QNX [man page](http://www.qnx.com/developers/docs/6.5.0SP1.update/com.qnx.doc.neutrino_lib_ref/g/getaddrinfo.html) says is perfectly valid.


I'll continue a bit longer to try to figure out what is going on. If you have any other thoughts on what areas I should focus on that would be appreciated.

**Comment by mbush00** [comment] 2018-07-19 13:16
I should also add that the behaviour is similar if using IPC:

$ ./reqrep server ipc:///tmp/test
SERVER: RECEIVED DATE REQUEST
SERVER: SENDING DATE: Thu Jul 19 13:17:58 2018

$ ./reqrep client ipc:///tmp/test
CLIENT: SENDING DATE REQUEST
CLIENT: RECEIVED DATE: Thu Jul 19 13:17:58 2018
$ ./reqrep client ipc:///tmp/test
CLIENT: SENDING DATE REQUEST

**Comment by gdamore** [comment] 2018-07-20 07:17
Well, if IPC fails, then that's not going to be related to getaddrinfo obviously. :-)

My first instinct here is that we have a descriptor or file that is not being closed all the way, but I'm not 100% certain.  I'd maybe look at the pipe notification stuff, to see if connect is causing the pipes to be connected at both the client and the server.  My first instinct is that the second instance isn't getting connected for some reason.

**Comment by gdamore** [comment] 2018-07-20 07:19
One thought that does occur to me.  Can you try inserting a delay -- say 10 ms or something like that, after the nng_dial and before the nng_send in the client?  This may be related to a different bug.

**Comment by mbush00** [comment] 2018-07-20 15:42
Agreed re: getaddrinfo() -- it's not related to this issue,  I just mentioned it because QNX seems to differ in behaviour.

I looked for any left opened file descriptors, and did not find any.

I also tried inserting the delay between nng_dial() and nng_send(); didn't help. I also tried varying the delay upto 100ms; again no change.

**Comment by gdamore** [comment] 2018-07-20 16:00
That’s pretty strange.  Can you see the connection is actually being
established?

**Comment by mbush00** [comment] 2018-07-20 17:31
Yes I can see the connection is established, and the client is waiting for the server:

'pidin fd' shows the open file descriptors and I can see the following:

1009389606 ./reqrep
0  479256 rw        0 /dev/ttyp0
1  479256 rw        0 /dev/ttyp0
2  479256 rw        0 /dev/ttyp0
3       6 r-        0 (pipe)
4       6 -w        0 (pipe)
5  389138 rw        0 I4TCP  192.168.8.111.8899    *.*                   LISTEN
6  389138 rw        0 I4TCP  192.168.8.111.8899    192.168.8.14.56651    ESTABLISHED
0s      1

The client is connected..

I dug a bit further, and I was able to fix the issue, however without spending more time to understand the codebase I am unsure if this is a proper fix.

So this is what I saw (QNX 'pidin threads' ) before and after the first time a client connects:

1011904550 ./reqrep              1                    CONDVAR     (0x14e1e8)
1011904550 ./reqrep              2                    SIGWAITINFO
1011904550 ./reqrep              3                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              4                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              5                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              6                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              7                    CONDVAR     (0x14b04c)
1011904550 ./reqrep              8                    CONDVAR     (0x14b04c)
1011904550 ./reqrep              9                    CONDVAR     (0x14b04c)
1011904550 ./reqrep              10                   CONDVAR     (0x14b04c)
1011904550 ./reqrep              11                   CONDVAR     (0x13fe30)
1011904550 ./reqrep              12                   CONDVAR     (0x13feac)
1011904550 ./reqrep              13                   CONDVAR     (0x13f558)

When I connect the second time and it locks up I see this:

1011904550 ./reqrep              1                    CONDVAR     (0x14e1e8)
1011904550 ./reqrep              2                    SIGWAITINFO
1011904550 ./reqrep              3                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              4                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              5                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              6                    CONDVAR     (0x13ffcc)
1011904550 ./reqrep              7                    NANOSLEEP
1011904550 ./reqrep              8                    CONDVAR     (0x14b04c)
1011904550 ./reqrep              9                    CONDVAR     (0x14b04c)
1011904550 ./reqrep              10                   CONDVAR     (0x14b04c)
1011904550 ./reqrep              11                   CONDVAR     (0x13fe30)
1011904550 ./reqrep              12                   CONDVAR     (0x13feac)
1011904550 ./reqrep              13                   CONDVAR     (0x13f558)

That nanosleep can be traced to the following snippet of code:

```
void
nni_plat_cv_init(nni_plat_cv *cv, nni_plat_mtx *mtx)
{
	// See the comments in nni_plat_mtx_init.  Almost everywhere this
	// simply does not/cannot fail.

	while (pthread_cond_init(&cv->cv, &nni_cvattr) != 0) {
		nni_msleep(10);
	}
	cv->mtx = mtx;
}
```

In mycase pthread_cond_init() is returning EBUSY which according to the man page says the following:

EBUSY - Previously initialized condition variable, cond, hasn't been destroyed. 

I changed it to:

```
void
nni_plat_cv_init(nni_plat_cv *cv, nni_plat_mtx *mtx)
{
	// See the comments in nni_plat_mtx_init.  Almost everywhere this
	// simply does not/cannot fail.
	int cond = 0;
	while ( (cond = pthread_cond_init(&cv->cv, &nni_cvattr)) != 0 && cond != EBUSY) {
		nni_msleep(10);
	}
	cv->mtx = mtx;
}
```

and this seems to fix the issue. I can re-run the client (tcp & ipc) and it works as expected.

**Comment by gdamore** [comment] 2018-07-20 18:23
This is quite interesting, and surprising.  I'm concerned that this indicates some problem somewhere where a condvar is getting doubly allocated, e.g. two calls to nni_plat_cv_init().  On most platforms this is probably harmless, but it does indicate a bug, as its not harmless everywhere (as you've seen!)

Can you possibly provide a backtrace, or the call site, where nni_plat_cv_init() was being called?  I'd like to investigate this further.

**Comment by mbush00** [comment] 2018-07-20 19:23
My GDB skills are limited and I'm cross compiling for a host with no compiler on it, so I just printed out every caller to nni_cv_init(). The output is below. 

NOTE: in nni_thr_init() [thread.c] you have an explict call to nni_plat_cv_init() where everywhere else it's wrapped in nni_cv_init(). Not sure if that was done on purpose or should be changed to nni_cv_init().

$ ./reqrep server tcp4://192.168.8.111:8899
nni_cv_init: called from nni_posix_resolv_sysinit
nni_cv_init: called from nni_taskq_init
nni_cv_init: called from nni_taskq_init
nni_cv_init: called from nni_reap_sys_init
nni_cv_init: called from nni_reap_sys_init
nni_cv_init: called from nni_timer_sys_init
nni_cv_init: called from nni_timer_sys_init
nni_cv_init: called from nni_aio_sys_init
nni_cv_init: called from nni_sock_create
nni_cv_init: called from nni_sock_create
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_posix_pfd_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_posix_pfd_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_pipe_create
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
SERVER: RECEIVED DATE REQUEST
SERVER: SENDING DATE: Fri Jul 20 19:19:57 2018
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init

** Second time running the client **

nni_cv_init: called from nni_posix_pfd_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_task_init
nni_cv_init: called from nni_pipe_create

** Server is now spinning in nni_plat_cv_init() due to EBUSY **

**Comment by gdamore** [comment] 2018-07-20 20:46
This was helpful.  I *think* the problem is that we are failing to call nni_cv_fini() in pipe_destroy().

This leaks resources, but its worse on your platform, because I think what is happening is that the allocator may be giving us back the same pipe structure we freed earlier.

That said, I'm still surprised because nni_alloc() should have calloc'd the data on POSIX.

Maybe you can retest with the commit I just made?

**Comment by mbush00** [comment] 2018-07-23 12:22
Gave it a test. That seems to have fixed it.

**Comment by gdamore** [comment] 2018-07-23 15:38
Awesome, closing this.

**Closed by gdamore** 2018-07-23 15:38 UTC
