### ISSUE TITLE
sub0 nng_msg_header_len always got zero length with a binary message body

### ISSUE THREAD

**Issue by bwlee** [nanomsg/nng#748] opened 2018-10-11 04:32 UTC
Ubuntu Linux 16.04.1-Ubuntu SMP 

pub/sub insert filter string with `nng_msg_header_insert()`,  and append binary data to message body with `nng_msg_append()` .

Also,  options  NNG_OPT_SENDBUF and NNG_OPT_RECVBUF both set to 10 messages, but always got empty message header when sub side received msg, and checked header contains inside at the beginning of message body.  also,  got a larger size than send message size (header plus body), a little more than double size.

on pub side:

```c++
  if ((rv = nng_setopt_int(pubsub, NNG_OPT_SENDBUF, 10)) != 0) {
    logger->error("server set send buf error, detail: {}", nng_strerror(rv));
  }
 // prepared data with size
....
  nng_msg *msg;
  if((rv = nng_msg_alloc(&msg, size)) != 0) {
    logger->error("nng_msg_alloc: {}", nng_strerror(rv));
  }
  string &&symbol = tick.symbol();
  nng_msg_header_insert(msg, symbol.c_str(), symbol.length() + 1);
  nng_msg_append(msg, data, size + 1);
  if ((rv = nng_sendmsg(pubsub, msg, 0)) != 0) {
  // if ((rv = nng_send(pubsub, data, size, 0)) != 0) {
    logger->error("server failed, nng_sendmsg error: {}", nng_strerror(rv));
  } else {
    logger->info("send data size = {}", size);
  }
```

on sub side:

``` c++
 if ((rv = nng_recvmsg(receiver, &msg, 0)) != 0) {
      logger->error("nng_recv: {}", nng_strerror(rv));
    }
    size_t hlen = nng_msg_header_len(msg);
    sz = nng_msg_len(msg);
    logger->debug("CLIENT: RECEIVED size = {}\n", sz);
    data = nng_msg_body(msg);
```
     where we can see msg header inside data, but have zero length message header.

I check all test code and found only example with string message, thanks for help or any hints!

**Comment by bwlee** [comment] 2018-10-11 09:20
also test with such code,  it seemed msg header and body combined when received by subscriber.

```sh
index d12a2df3..39207ac8 100644
--- a/tests/pubsub.c
+++ b/tests/pubsub.c
@@ -17,7 +17,8 @@
 
 #include <string.h>
 
-#define APPENDSTR(m, s) nng_msg_append(m, s, strlen(s))
+#define APPENDHEADER(m, s) nng_msg_header_append(m, s, strlen(s))
+#define APPENDSTR(m, s) nng_msg_append(m, s, strlen(s) + 1)
 #define CHECKSTR(m, s)                   \
        So(nng_msg_len(m) == strlen(s)); \
        So(memcmp(nng_msg_body(m), s, strlen(s)) == 0)
@@ -112,7 +113,8 @@ TestMain("PUB/SUB pattern", {
                        So(nng_setopt_ms(sub, NNG_OPT_RECVTIMEO, 90) == 0);
 
                        So(nng_msg_alloc(&msg, 0) == 0);
-                       APPENDSTR(msg, "/some/like/it/hot");
+                       APPENDHEADER(msg, "/some/");
+                       APPENDSTR(msg, "like/it/hot");
                        So(nng_sendmsg(pub, msg, 0) == 0);
                        So(nng_recvmsg(sub, &msg, 0) == 0);
                        CHECKSTR(msg, "/some/like/it/hot");
lines 14-36/36 (END)
```

**Comment by gdamore** [comment] 2018-10-11 14:36
The pub/sub protocols do not use the message header. In general you should
not be using the message header at all unless you are using a raw mode
protocol and understand the particulars of how the protocol uses the
header.

For pub/sub the topic is just the first bytes of the message.

On the wire there is no special delimiter for the header. Instead the
header is decided by checking for certain numerical values (for the
protocols that use them such as req/rep).

On send the message header and body are just concatenated together.  So the
receiver just sees them as a single message body.

Upshot here is that attempts to use the header for pub/sub are misguided.

 - Garrett

**Comment by gdamore** [comment] 2018-10-11 18:20
So NNG is behaving as intended here.  I'm going to close this.  If you still have questions about this, you can post them here, and I will reply.

**Closed by gdamore** 2018-10-11 18:20 UTC
