### ISSUE TITLE
Massive message loss with Pair v1 Polyamorous

### ISSUE THREAD

**Issue by amunhoz** [nanomsg/nng#1274] opened 2020-08-03 23:44 UTC
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
nng 1.3.0
ubuntu 18.04
using nngpp wrapper to c++ 

## Expected Behavior
I'm using nng to create another kind of message broker, using nng pair poly to act as a server to many peers.
I try to send 10000 messages to the other pair, to test.  And is expected to receive each one on the other side.

## Actual Behavior
When using polyamorous, even with only two peers (server/client) it lost a massive amount of messages.  The same problem does not happen with normal pair connections between the two peers.
It loses around 30% of the messages.

## Steps to Reproduce
```
   // nng::socket socks = nng::pair::v1::open();      //the problem does not happen with normal pair
    nng::socket socks = nng::pair::v1::open_poly();      
    socks.listen("ipc:///tmp/testz.ipc");     

    nng::socket sockc = nng::pair::v1::open();                
    sockc.dial("ipc:///tmp/testz.ipc");   

    int countReceive = 0;
    std::thread nativeThread = std::thread( [&countReceive, &sockc] {                                  
        while(true) {            
            nng::msg msg;
            msg = sockc.recv_msg();              
            countReceive++ ;          
        }                              
    });
           
    char * test = "hidata";
    for(int i=1; i<=10000; i++){
        auto msg = nng::make_msg(0);   
        msg.body().append(nng::view(test,(int)6) );  
        socks.send( std::move(msg) );
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(1000)); //delay audio a little, just to sync
    std::cout << "received " << countReceive << std::endl;   
    // Result is 'received 7354', it should be 'received 10000'.
    // with different direction (sockc->socks) or without polyamorous it worked well

```

**Comment by amunhoz** [comment] 2020-08-04 14:27
i've had some problems before because the attemp to integrate do node-addon-api.  But i believe this problem is related to nng.  With the change in the protorocol (without poly) and direction, it works fine.

**Comment by gdamore** [comment] 2020-08-04 17:58
Polyamorous is best effort delivery only, and if you send faster than than you can receive (or faster than the pipe can transport the messages), the messages get dropped.  This is by design, to prevent a slow reader from stopping message delivery from other readers.

When you aren't using polyamorous mode, we can reasonably apply backpressure, so we slow down the transmission rate instead of dropping the message.

**Comment by amunhoz** [comment] 2020-08-04 18:16
Does it supose to happen even with only two peers and only in the listen->dialer direction?  
Is there any way to detect if it was delivered?  I think the send command is returning 0 without any problem.

**Comment by gdamore** [comment] 2020-08-08 18:06
Yes, it happens in any case.  The socket doesn't know or care how many peers are connected.  If you want 1:1 reliable comms, don't use polyamorous mode.

And indeed, there is no error returned.  The successful return means the socket has accepted the message for delivery and will do it's best to send it to all connected peers.  If any can't send it at that time, it gets discarded.  A single error is insufficient to indicate partial success/failure.

**Comment by gdamore** [comment] 2020-08-08 18:08
It's not dialer/listener direction that matters, but whether poly is sending or the non-poly mode is.  The poly mode drops on send, not on receive.  Non-poly peers will block because as far as they know, they are only speaking with a single peer.

**Comment by gdamore** [comment] 2020-08-08 18:08
I'm closing this as it's not a defect, but behaving as designed.

**Closed by gdamore** 2020-08-08 18:08 UTC
Labels: feedback
