### ISSUE TITLE
higher latency than zmq with small message

### ISSUE THREAD

**Issue by sherlockkenan** [nanomsg/nng#560] opened 2018-06-30 15:04 UTC
Hi,
recently, I used the nng to replace the zmq in our project. however, In our test,  I find that nng（or nanomsg) has  higher latency than zmq with small message (less than 1M byte). 
I use two nodes do the test.  one send one message to the other node. the other node receive the message and send it  back.  I calculate the time of such one round-trip.  Both nng and zmq use the pipeline model. and the code is almost the same as the example of nng and zmq.

here is the result : 

latency（us） | 10 byte | 100 byte | 1000 | 10K | 100K | 1M | 10M|
-- | -- | -- | -- | -- | -- | -- | --
nng | 140 | 143 | 172 | 733 | 1231 | 8857 |  83472|
zmq  | 68 | 77 | 96 | 240 | 778 | 8143 | 81456

is that right? or is that any methods to reduce the latency of nng?

**Comment by gdamore** [comment] 2018-06-30 16:20
I'm not sure which transport you're using, as that could make a real difference.  I'd also like to know the platform.

Also, if you're making a test using a naive simple send and recv, then you should be advised that this does not reflect actual usage.  In particular, nng is designed so that the same code paths are used regardless of whether an application is concurrent or single threaded.  This means that your latency measurements for a naive app have the same overheads as a highly concurrent app, whereas ZMQ (and nanomsg as well) are designed so that a single threaded app pays no concurrency overhead, but as soon as you have any concurrency there is a big spike in the latency as suddenly several extra system calls (poll, read, write) need to be added.  

I have a plan to write some test programs demonstrating this, with a blog post, I just haven't gotten around to it yet.

Having said that, I am well aware that nng is not yet fully optimal.  There are lots of places for optimizations and improvements -- nng is still a "young" project in that regard.  We have several open bugs here for this.

**Comment by gdamore** [comment] 2018-06-30 16:20
Any chance I can get you to post your example program, as well as details on the platform where it was run?

**Comment by sherlockkenan** [comment] 2018-07-01 08:42
thank you for your answer. 
Platform:ubuntu 14.04.here is my example program,
for zmq:

```
#include <boost/mpi.hpp>
#include <iostream>
#include <map>
#include "timer.hpp"
#include <nng/nng.h>
#include <nng/protocol/pipeline0/push.h>
#include <nng/protocol/pipeline0/pull.h>
#include <zmq.hpp>
using namespace std;


int main(int argc, char *argv[])
{

    int num=atoi(argv[2]);
    int size =atoi(argv[3]);
    // construct the send message
    string send_msg;
    for (int i = 0; i < size; i++ ){
        send_msg += "a";
    }
    char *send_message = new char[send_msg.length() + 1];
    strcpy(send_message, send_msg.c_str());

    boost::mpi::environment env(argc, argv);
    boost::mpi::communicator world;
    int sid = world.rank(); // server ID

    int sum = 0;
    zmq::context_t context;
    zmq::socket_t * send_sock;
    zmq::socket_t * recv_sock;
    int rv;
    //init the sockket 
    if(sid == 0){
        recv_sock = new zmq::socket_t(context, ZMQ_PULL);
        recv_sock->bind("tcp://*:9576");
        send_sock = new zmq::socket_t(context, ZMQ_PUSH);
        send_sock->connect("tcp://10.0.0.103:9776");
    } else {
        recv_sock = new zmq::socket_t(context, ZMQ_PULL);
        recv_sock->bind("tcp://*:9776");
        send_sock = new zmq::socket_t(context, ZMQ_PUSH);
        send_sock->connect("tcp://10.0.0.100:9576");
    }

    // begin to send and recv the message
    for (int i =0; i< num; i++) {
        MPI_Barrier(MPI_COMM_WORLD);
        uint64_t start = timer::get_usec();
        // master node 
        if(sid == 0) {
            zmq::message_t s_msg(send_msg.length());
            memcpy((void *)s_msg.data(), send_msg.c_str(), send_msg.length());
            if(! send_sock->send(s_msg, ZMQ_DONTWAIT)){
                cout << " zmq_send error" <<endl;
            }
            zmq::message_t r_msg;
            if(recv_sock->recv(&r_msg) < 0) {
                cout<< " zmq_recv error"<<endl;
            }
        // the other node
        }else {
            zmq::message_t r_msg;
            if(recv_sock->recv(&r_msg) < 0) {
                cout<< " zmq_recv error"<<endl;
            }
            zmq::message_t s_msg(send_msg.length());
            memcpy((void *)s_msg.data(), send_msg.c_str(), send_msg.length());
            if(! send_sock->send(s_msg, ZMQ_DONTWAIT)){
                cout << " zmq_send error" <<endl;
            }
        }
        uint64_t end = timer::get_usec();
        sum += (end -start);
    }
    if(sid ==0)
        cout << " the average sending time "<< sum/num<< endl;
    send_sock->close();
    recv_sock->close();
    return 0;
}
```

for nng:

```
#include <boost/mpi.hpp>
#include <iostream>
#include <map>
#include "timer.hpp"
#include <nng/nng.h>
#include <nng/protocol/pipeline0/push.h>
#include <nng/protocol/pipeline0/pull.h>
using namespace std;


int main(int argc, char *argv[])
{
    int num=atoi(argv[2]);
    int size =atoi(argv[3]);
    // construct the send message
    string send_msg;
    for (int i = 0; i < size; i++ ){
        send_msg += "a";
    }
    char *send_message = new char[send_msg.length() + 1];
    strcpy(send_message, send_msg.c_str());

    boost::mpi::environment env(argc, argv);
    boost::mpi::communicator world;
    int sid = world.rank(); // server ID

    int sum = 0;
    nng_socket send_sock;
    nng_socket recv_sock;
    int rv;
    // init the sockket 
    if(sid == 0){
        if ((rv = nng_pull0_open(&recv_sock)) != 0) {
                cout<< "nng_pull0_open"<<endl;
        }
        if ((rv = nng_listen(recv_sock, "tcp://*:9576", NULL, 0)) != 0) {
                cout<<"nng_listen" << sid << endl;
        }
        if ((rv = nng_push0_open(&send_sock)) != 0) {
                cout<< "nng_pull0_open"<<endl;
        }
        if ((rv = nng_dial(send_sock, "tcp://10.0.0.103:9776", NULL, NNG_FLAG_NONBLOCK)) != 0) {
                cout<< "nng_dial"<<endl;
        }
    } else {
       if ((rv = nng_pull0_open(&recv_sock)) != 0) {
                cout<< "nng_pull0_open"<<endl;
        }
        if ((rv = nng_listen(recv_sock, "tcp://*:9776", NULL, 0)) != 0) {
                cout<<"nng_listen" <<endl;
        }
        if ((rv = nng_push0_open(&send_sock)) != 0) {
                cout<< "nng_pull0_open"<<endl;
        }
        if ((rv = nng_dial(send_sock, "tcp://10.0.0.100:9576", NULL, NNG_FLAG_NONBLOCK)) != 0) {
                cout<< "nng_dial"<<endl;
        }

    }

    // begin to send and recv the message
    for (int i =0; i< num; i++) {
        MPI_Barrier(MPI_COMM_WORLD);
        uint64_t start = timer::get_usec();
        // master node 
        if(sid == 0) {
            if ((rv = nng_send(send_sock, send_message, size+1, 0)) != 0) {
                cout << "nng_send error" <<endl;
            }
            char *buf = NULL;
            size_t sz;
            if ((rv = nng_recv(recv_sock, &buf, &sz, NNG_FLAG_ALLOC)) != 0) {
                cout<< "nng_recv error"<<endl;
            }
        // the other node
        }else {
            char *buf = NULL;
            size_t sz;
            if ((rv = nng_recv(recv_sock, &buf, &sz, NNG_FLAG_ALLOC)) != 0) {
                cout<< " nng_recv error"<<endl;
            }
            if ((rv = nng_send(send_sock, send_message, size +1, 0)) != 0) {
                cout << " nng_send error" <<endl;
            }
        }
        uint64_t end = timer::get_usec();
        sum += (end -start);
    }
    if(sid == 0)
        cout << " the average sending time "<< sum/num<< endl;

    return 0;
}
```

when running the program with argument(like size=1000，num =100），the ngg is  2~4 times slower than zmq.   Thank you for your help~

**Comment by gdamore** [comment] 2018-07-01 16:41
Thanks.  I see a few problems in the code.  First, the code is a benchmark special, so it won't behave in a way that represents a real concurrent program.  (You have only a single thread that does send and receive.  This is not most interesting programs, and as I indicated before, ZMQ and nanomsg backend architecture favors this design at expense of real world programs.  NNG uses the same approach for all programs.)

The other thing is that you're doing your sends in a way that guarantees extra data copies for nng, and you're not deallocating received messages in your nng example, which ultimately leads to increased pressure on the heap.  NNG_FLAG_ALLOC is intended to reduce data copies, but is not as good as using preallocated nng_msg structures.  It gives little benefit if you don't reuse the allocated structure, since you're not just copying data, but also reallocating with no reuse.

For performance critical code paths, you should preallocate a message structure (nng_msg_alloc()) and then send that message using nng_send_msg().  You can use the same message you get from nng_msg_recv() with nng_msg_send() as well.

I should probably further clarify this in the documentation.

I'll see if I can come up with some better performance demonstrations to show how nng compares against ZMQ and legacy nanomsg.  I expect ZMQ and nanomsg (especially the latter) to beat NNG in benchmark specials, but for NNG win once you add multiple sockets being accessed concurrently.

**Comment by sherlockkenan** [comment] 2018-07-05 06:07
thanks a lot.  In my project, it  behave may like this special benchmark.  So I consider the nanomsg is more suitable for us.  Thanks again for your help.

**Comment by sherlockkenan** [comment] 2018-07-05 09:24
when I turn to evaluate the nanomsg with previous microbenchmark,  I find that its average latency(10000 times average ) is almost the same as zmq.  However, in some special  case, the latency is 100x slower than usual.

for example,the the latency of second time to send message is much higher than others.
```
the sending time 1068
 the sending time 37621
 the sending time 225
 the sending time 232
 the sending time 105
 the sending time 155
 the sending time 121
 the sending time 110
 the sending time 104
 the sending time 105
 the sending time 110
 the sending time 111
 the sending time 111
 the sending time 99
 the sending time 100
 the sending time 109
 the sending time 106
 the sending time 144
 the sending time 137
 the sending time 111
 the average sending time 2049
```
Therefore if I run 10000 times, the average latency of zmq and  nanomsg are almost the same. but if I  just run 100 times, the latency fo nanomsg is higher than zmq. 

and there are also  some  special cases  causing higher latency, for example, if the sending size = 1000 and after  200 times sending , the sending  time also turn to much higher.

What may cause such special case and Can I avoid it ?

Here is the code I used for test:
```
#include <boost/mpi.hpp>
#include <iostream>
#include <map>
#include "timer.hpp"
#include <boost/program_options.hpp>
#include <nanomsg/nn.h>
//#include <nng/protocol/pipeline0/push.h>
//#include <nng/protocol/pipeline0/pull.h>
#include <nanomsg/pipeline.h>
using namespace std;
using namespace boost::program_options;



int sid;

#define thread_id (0)
#define master_sid (0)
#define slave_sid (1)
#define IS_MASTER(_p) ((_p) == 0 )
int recv_sock;
int send_sock;
char* c_msg;
// init socket
void init_socket()
{
    int rv;
    if(IS_MASTER(sid)){
        if ((recv_sock = nn_socket(AF_SP, NN_PULL)) < 0) {
                cout<< "nn_pull_open error"<<endl;
        }
        if ((rv = nn_bind(recv_sock, "tcp://*:9576")) < 0) {
                cout<<"nn_bind error" << sid << endl;
        }
        if ((send_sock = nn_socket(AF_SP, NN_PUSH)) < 0) {
                cout<< "nn_push_open error"<<endl;
        }
        if ((rv = nn_connect(send_sock, "tcp://10.0.0.103:9776")) < 0) {
                cout<< "nn_connect error"<<endl;
        }
    } else {
        if ((recv_sock = nn_socket(AF_SP, NN_PULL)) < 0) {
                cout<< "nn_pull_open error"<<endl;
        }
        if ((rv = nn_bind(recv_sock, "tcp://*:9776")) < 0) {
                cout<<"nn_bind error" << sid << endl;
        }
        if ((send_sock = nn_socket(AF_SP, NN_PUSH)) < 0) {
                cout<< "nn_push_open error"<<endl;
        }
        if ((rv = nn_connect(send_sock, "tcp://10.0.0.100:9576")) < 0) {
                cout<< "nn_connect error"<<endl;
        }
    }
}

void * send ()
{
    int bytes;
    if(bytes = nn_send(send_sock,c_msg,strlen(c_msg)+1, 0) < 0) {
        cout << "nn _send error" <<endl;
    }
}

void * recv() 
{
    char* buf;
    int bytes;
    if(bytes = nn_recv(recv_sock,&buf,NN_MSG, 0) < 0) {
        cout << "nn _send error" <<endl;
    }
    nn_freemsg(buf);
}


int main(int argc, char *argv[])
{
    int size = argv[3];
    int num = argv[2];
   string send_msg;
    for (int i = 0; i < size; i++ ){
        send_msg += "a";
    }
    c_msg= new char[send_msg.length()+1];
    strcpy(c_msg,send_msg.c_str());

    boost::mpi::environment env(argc, argv);
    boost::mpi::communicator world;
    sid = world.rank(); // server ID

    // set the address file of host/cluster
    init_socket();

    int sum = 0;

    // begin to elvation the latency
    for (int i =0; i< num; i++) {
        MPI_Barrier(MPI_COMM_WORLD);
        uint64_t start = timer::get_usec();
        if(IS_MASTER(sid)) {
            send();
            recv();
        }else {
            recv();
            send();
        }
        uint64_t end = timer::get_usec();
        if(IS_MASTER(sid))
            cout << " the sending time "<< end -start<< endl; 
        sum += (end -start);
    }

    if(IS_MASTER(sid))
        cout << " the average sending time "<< sum/num<< endl; 
    return 0;
}

```

**Comment by gdamore** [comment] 2018-07-05 14:19
My first guess is that those extremely high latencies are due to TCP backpressure or even slowdowns caused by packet loss.

I would be surprised if your real-world program isn't quite as much like these examples as you think.  Generally speaking, most programs want to have some other I/O to interact with, which means usually that they either make use of poll() or are multithreaded or something similar.  The other use cases are most often programs that are short lived, where latency is not the single most important thing to optimize for.  (For example, program startup times and TCP connect times generally take a lot longer than the latency to send a single message.)

**Comment by gdamore** [comment] 2018-07-05 14:28
Actually those long times are about the right length that they may be your
program getting context switched away from the CPU.  Do you have anything
else running on the system ?

**Comment by sherlockkenan** [comment] 2018-07-08 14:33
it does not caused by  context switched. Because  I run it  many times, and always the first and second  get extremely high latencies, especially the second.

**Comment by sherlockkenan** [comment] 2018-07-08 14:46
if I delay  some time(using sleep function) in the critical code paths, it will not meet extremely high latencies like the second times. But the all latency are similar to the first time, which also get high latency.

Is there any ways to avoid the  extremely high latency?

**Comment by gdamore** [comment] 2018-07-08 15:35
So I think you had longer latency because you were sending before the connection was established?

I also see you closed the issue... why did you close it?

**Comment by gdamore** [comment] 2018-10-27 04:51
I'm wondering if the issue is TCP deferred ack.... but I need to set up some kind of performance tests....  really I need a better system for benchmarking this because the Mac is horrible at it.

**Comment by gdamore** [comment] 2020-01-20 03:46
I just had another look at this.

I know what is happening.

You're using the legacy nanomsg API, which does nn_connect() *asynchronously*.

This causes the first message (or maybe two?) to encounter the latency caused by setting up the connection.  A *very* simple solution to this would be to insert a brief delay (a few dozen milliseconds for a crummy TCP connection, or perhaps just a few dozen microseconds if using inproc or only loopback connections on a host with excellent loopback TCP setup code.)

If you use the modern NNG API, this doesn't happen (mostly).  nng_dial() by default does not return until the connection is established.  (Unfortunately there may still be some asynchronous setup happening on the far side -- there isn't a way to make accept() truly synchronous.)

What I've done in my own tests is to use out of band signaling and pipe events to alert readiness.  Have a look at the recent code -- tests/testutil.c -- and testutil_marry() in particular.  That should allow you to defer the start of the test to the point that you actually have things fully established.

(Note that it should be clear here that NNG is not optimized for short-lived connections -- it is largely assumed that NNG participants will have long lived connections.)

**Comment by gdamore** [comment] 2020-01-20 03:47
Actually, I know why it is the *2nd* message too.  We return right away to the client once we've identified that a pipe is able to accept a message.  But that doesn't really mean we're fully open on the other side -- so while the first message is waiting to be handled by the remote side, the 2nd message gets the penalty.

**Comment by gdamore** [comment] 2020-01-20 03:48
If you wouldn't mind seeing if you can change your test as indicated ... if this doesn't solve the problem let me know.  Otherwise I'll probably close this ticket in a week or so if I don't hear otherwise from you.  (Sorry it took so long to get back on this.)

**Comment by kasunch** [comment] 2020-02-12 08:30
I just ran a blind perf test without going into details with  "inproc_lat 100 1000" for both nng and zmq. 
On my Linux laptop, nng has over 50 us latency in most cases (varies a lot) while zmq is having consistently below 20 us latency. Any idea?

**Comment by gdamore** [comment] 2020-02-25 07:10
that's quite possibly just thread dispatching costs.  NNG definitely pays slightly more for some of these depending on the thread library -- we go through several thread dispatches that ZMQ avoids by running everything in a single event loop.  But that also means we can scale out horizontally better.  So it's kind of a tradeoff -- pick your poison.

There's still stuff we can do though.  It looks like we're doing at least one extra allocation that I am about to eliminate.

**Comment by gdamore** [comment] 2020-12-28 01:15
I'm closing this for now... there is no question that in some circumstances ZMQ will have lower latency -- but *only* if you have a program that doesn't need to interact with a poll/select loop.  Or is threaded.  ZMQ is not thread-safe, NNG is.  That comes at a cost. 

A lot of work has been done since this was filed to attempt to reduce latencies overall.  Of course, its going to depend a lot on the underlying platform.

Anyway feel free to give it another shot.

**Closed by gdamore** 2020-12-28 01:15 UTC
Labels: feedback, performance
