### ISSUE TITLE
How to start getting involved

### ISSUE THREAD

**Issue by kitofans** [nanomsg/nng#159] opened 2017-11-26 21:16 UTC
I would like to see if I can help contribute to this project. In particular, I'm looking for a lightweight, extendable framework that would support raw UDP transport methods / transport built on top of UDP for very low latency (though unreliable) message passing -- a primary use case would be multiplayer games. 

nng seems to fit the bill for what I am looking for, and given it's stage, I might be able to help move it along (in particular, there seems to be some UDP implementation in support of ZeroTier but not a direct UDP transport yet). However, given the lack of high-level documentation and design goals, I am not sure how to start. 

My understanding of the library design is as follows:

'protocols' are patterns of message passing; the messages themselves are sent via 'transports'. The design is such that as long as you implement a new 'transport' in the correct way, every 'protocol' can make use of it efficiently. Similarly, you can implement a new 'protocol' and have it work with every 'transport'. 

The work required to implement a new 'transport' is simply making it conform the some 'transport api' that nng defines (I have not explicitly found this, however). So, if there is some other library implementing a transport type (say, for example, https://github.com/zaphoyd/websocketpp), you could implement that as a nng transport type by wrapping it in nng's api (though, for websockets, since they are so common, I would imagine nng would implement it directly -- another, perhaps better example would be ENet: https://github.com/lsalzman/enet, which is a popular UDP-based transport method)

Is this about correct? I do realize that in general most of the 'ships with nng' transports would be directly implemented in nng (rather than wrapping some other library like websocketpp or enet), but I am trying to understand the design goals and abstractions here.

**Comment by gdamore** [comment] 2017-11-26 22:09
You have a pretty good understanding.  The transport API is in src/core/transport.h, but not yet "complete" and certainly totally undocumented.  At this point I'm the only one working on nng implementation, but I'd welcome more participation.

nng itself is quite young, and I'm not yet recommending it for production use.

With respect to UDP, there is a draft RFC up at the nanomsg site, but I think I'm probably going to wind up extending upon that a bit - leveraging things I learned while doing the ZeroTier tier transport.  Its kind of low priority.

For some applications, a stream transport like KCP that operates over UDP might solve many of the latency issues with TCP.  I have a plan to do a KCP transport in the future.

I'm actively at work on the websocket transport, which will include TLS support.  I expect within a week or two I'll have something for folks to start playing with.

(In terms of UDP, I am thinking specifically of adding a message fragmentation layer to support sending larger messages -- I think it can be usable for messages up to say 1MB or so.  Admittedly, applications that are concerned with operating over long haul or lossy networks should try to use smaller message sizes -- 1400 bytes or so (allowing for the various headers) is about the largest that can be reliably transported across most internet links without fragmentation.)

**Comment by kitofans** [comment] 2017-11-27 00:56
I see. So, if I understand correctly, your stance is something along the lines of 'I'd appreciate help, but potential helpers must be brave souls willing to understand the library via source rather than documentation'. I'll peruse a bit and see if I fit the bill.

I hadn't seen KCP before. It looks interesting, but is still reliable (albeit UDP), which will always be suboptimal for some use cases (namely, multiplayer games, where in some cases dropped packets are useless to resend since more recent packets supercede them anyways).

As for UDP, you might actually be interesting in looking at ENet (http://enet.bespin.org/Features.html). It is a connection-based transport method over UDP that allows sending packets either reliably or unreliably. It also supports fragmentation, which, as you mentioned, is important for larger messages. It's API is also pretty similar to the transport API (as i understand it), so it might be an easy addition.

As a side question (regardless of whether or not you are actually interested in ENet), just for my own understanding of the library's semantics, consider the following ENet concept. When a connection is made between two endpoints, as mentioned above, data can be sent either reliably or unreliably. Reliable packets force the receiver to block until the correct ordering of packets is respected, which is unfortunate for use cases where some packets are sent reliably and some are unreliable, since the reliable ones might block the unreliable ones. For this reason, ENet allows you to allocate multiple 'channels' through which you send packets, and each channel is independently sequenced, so that sending a reliable packet through channel 0 will not block unreliable packets on channel 1 (for example).

Would these semantics fit into nanomsg's design? And if so, how would you implement it? Based on my current read of the interface (early stages so I could be wrong), perhaps you would actually implement different channels as different 'pipes' in the transport (even though under the hood they are being sent through one connection)?

**Comment by gdamore** [comment] 2017-11-28 15:31
The situation you describe is analogous to what we do in the ZeroTier
transport. Each channel would be its own pipe.

**Comment by gdamore** [comment] 2017-12-27 00:24
Closing this -- its a question not a bug.

**Closed by gdamore** 2017-12-27 00:24 UTC
