### ISSUE TITLE
Question about raw vs. cooked REQ socket message body sizes

### ISSUE THREAD

**Issue by klemen-forstneric** [nanomsg/nng#900] opened 2019-02-28 10:40 UTC
## NNG & Platform details.

nng 1.1.1, OS X, Clang (Apple LLVM version 10.0.0)

## Expected Behavior

Message body sizes should be the same when sent either through raw or cooked socket.

## Actual Behavior

The body of the message is 4 bytes shorter (and the header is 4 bytes longer) when sent through a raw REQ socket. This transformation does not happen when using cooked socket.

## Steps to Reproduce

Take the example located in `demo/raw` and create a REQ socket in raw mode using `nng_req0_open_raw` instead of `nng_req0_open`.

What's the rationale behind this? Should I be prepending a 32 bit value to all my messages when sending them in raw mode? I wasn't able to find anything in the docs on the website.

**Comment by gdamore** [comment] 2019-03-02 18:42
Raw mode is not for "normal" application use, but works with message bodies with the NNG specific header fields inlined in the message body.  This is used by the nng_device() framework.  It used to be that raw mode was necessary to create applications which supported concurrent outstanding operations on a socket, but that's no longer true -- the new way with NNG is to use contexts (see nng_ctx_open()) for protocols that have meaningful state (such as REQ sockets).

Generally speaking, unless you have some specific need to access the message headers, you should not use raw mode sockets.

An argument *could* be made that raw mode should move the message headers into the actual header field, but that would break many applications which are designed around raw mode.  Additionally, there are raw mode applications which use the simpler nng_send() and nng_recv() (and thus have no way to access the actual message structure itself.)

I hope this makes things a bit clear. 

As this is just a clarification, I'm closing this as it's not a bug, and nothing further is actionable apart from answering the question.

**Closed by gdamore** 2019-03-02 18:42 UTC
