### ISSUE TITLE
NNG to FreeRTOS

### ISSUE THREAD

**Issue by EduardShaid** [nanomsg/nng#609] opened 2018-07-27 14:05 UTC
Is it possible to expect the porting of the NNG to FreeRTOS ?

**Comment by gdamore** [comment] 2018-07-27 17:19
This is actually filed as ticket #15 -- I'd like to get to this, but there hasn't been much urgency in doing so because nobody has requested it.  If you're requesting it, that helps.  If you need it commercially, your company can sponsor this work -- contact info@staysail.tech for pricing details.

**Comment by SG7** [comment] 2019-01-24 23:02
With current investment by Amazon in FreeRTOS https://aws.amazon.com/freertos/
it makes sense that serious corporate sponsor should back up porting and testing NNG with FreeRTOS.
The scope of the nng project covers already a lot. Unless requests for porting NNG to some exotic or fringe OS is back up by the commercial sponsorship such port slows down the much more important improvements to the nng core.

**Comment by Kurdakov** [comment] 2019-03-02 17:15
stm has released STM32MP1 combo processor ( arm a7 + m4 ) and might be interested in a solution like nng (possibly they just missed an opportunity to consider such a solution as this combo  is a new offer). currently they offer amp for interprocessor communications in STM32CubeMP1, but nng will be much more useful. is anyone broker a deal with stm to support nng (explaining them all the benefits)- that will be great.

**Comment by raveslave** [comment] 2019-04-18 07:33
+1

**Comment by gdamore** [comment] 2020-01-21 15:59
I'm closing this as a duplicate of #15 for now.  I've add #15 to the roadmap for v1.4.

**Closed by gdamore** 2020-01-21 15:59 UTC

**Comment by Frank-KunLi** [comment] 2021-03-01 06:52
+1

**Comment by geraldolsribeiro** [comment] 2025-02-14 05:26
+1
