### ISSUE TITLE
On nng_sub0, receive notification also when filtered message

### ISSUE THREAD

**Issue by condo4** [nanomsg/nng#741] opened 2018-10-04 11:39 UTC
NNG v1.0.1 Linux

I'm working to integrate NNG into a Qt application.
I have an issue with the nng_sub0 protocol.
I used a QTcpNotifier on the fd returned by NNG_OPT_RECVFD to be wake when I need to read a message.

But, I received a notification also when nng received a filtered message.
So, In my program, when I received a notification, I'm reading message (by nng_recv), but in this case I'm entered in the blocking state.

Is there a way to know when we are notified, If there is really something to read OR, a way to be notify only when received a non-filtered message ?

**Comment by gdamore** [comment] 2018-10-04 14:11
This sounds like a potential bug in NNG itself. I will investigate.

**Comment by condo4** [comment] 2018-10-05 09:45
I worked deeper on this issue; in fact, the issue is very strange.
I wrote a simple program test in order to reproduce it without Qt and a complex application.
[TestNNG.tar.gz](https://github.com/nanomsg/nng/files/2449740/TestNNG.tar.gz)

In this test, there is a pub server, it send periodically 2 messages.
The first is totally text: "/toto/tutu 14.5"
The second, is a character ('b' by defaut, or use argv[1][0]), follow by a binary message

I wrote 2 clients:
The 'client_direct' use nng_recv in a  blocking mode.
The 'client' use nng_recv in a non blocking loop, by using select and NNG_OPT_RECVFD.

client and client_direct use a filter ('b' by default, or use argv[1][0]).

If I use filter '/', the 2 clients works well
if I use filter 'b', client_direct works well, but, client loose some messages, and after few second, select don't lock, but (FD_ISSET(fd,&fds)) is always false (this is I think, the same issue I have with QTcpSocketNotifier).

If I wrote something wrong, were is my mistake, or, there is a bug in libnng when using non blocking mode ?

I use v1.0.1 or master with the same issue, I'm working on Linux Debian Stable PC x86_64.

**Comment by condo4** [comment] 2018-10-05 14:52
I have more information, bug don't be linked to binary/text property of the message, but to the sent order.
So, many test:
If server loop is:
    while(1)
    {
        printf("send\n");
        nng_send(m_pub, buf, strlen(buf), 0); // text message
        nng_send(m_pub, msgp, 12, 0);         // binary message
        usleep(500 * 1000);
    }
-> client b; FAIL
-> client /; OK

    while(1)
    {
        printf("send\n");
        nng_send(m_pub, msgp, 12, 0);         // binary message
        nng_send(m_pub, buf, strlen(buf), 0); // text message
        usleep(500 * 1000);
    }
-> client b; OK
-> client /; FAIL

In all cases, client_direct works.

So, it seem to be an issue when the server sent 2 messages quickly, IF we filter the client on the second message...

**Comment by condo4** [comment] 2018-10-05 14:57
New server:

#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>

#include <nng/nng.h>
#include <nng/protocol/pubsub0/pub.h>

int main(int argc, char *argv[])
{
    int rv;
    nng_socket m_pub;
    char *buf1 = "1_message";
    char *buf2 = "2_message";
    char *buf3 = "3_message";

    if((rv = nng_pub0_open(&m_pub)) != 0)
    {
        printf("%s %i", "nng_pub0_open fail", rv);
        return -1;
    }

    if ((rv = nng_listen(m_pub, "tcp://*:6723", NULL, 0)) != 0)
    {
        printf("%s %i", "nng_listen", rv);
        return -1;
    }


    while(1)
    {
        printf("send\n");
        nng_send(m_pub, buf1, strlen(buf1), 0); // text message
        nng_send(m_pub, buf2, strlen(buf2), 0); // text message
        nng_send(m_pub, buf3, strlen(buf3), 0); // text message
        usleep(500 * 1000);
    }

    return 0;
}

In this case, 1 and 2 filter work, but not 3...

**Comment by gdamore** [comment] 2018-10-05 14:59
One thing I see is that you're sending messages in rapid succession.  The problem is that the if you have not arranged for message buffering, this can lead to lost messages.  Inject a 5 ms delay between those messages and it should probably just work.  Or set a longer queue depth (NNG_OPT_SENDBUF, set it to like 10 or more.  the count is messages.)

**Comment by gdamore** [comment] 2018-10-05 15:00
While here, lets also set the NNG_OPT_RECVBUF up a bit too.

**Comment by gdamore** [comment] 2018-10-05 15:04
Also your select() loop in the client is wrong.  The first argument to it should be *1*.  Otherwise you're asking select to go off and look in the weeds at file descriptors that are not part of your set.

**Comment by gdamore** [comment] 2018-10-05 15:05
Oh wait, never mind,  this is select() not poll().

**Comment by condo4** [comment] 2018-10-05 15:08
Ok, so I rewrite send write to:
    while(1)
    {
        printf("send\n");
        nng_send(m_pub, buf1, strlen(buf1), 0); // text message
        usleep(5 * 1000);
        nng_send(m_pub, buf2, strlen(buf2), 0); // text message
        usleep(5 * 1000);
        nng_send(m_pub, buf3, strlen(buf3), 0); // text message
        usleep(500 * 1000);
    }

In this case, I didn't loose message anymore, BUT, after some seconds, I have the client loop issue...

**Comment by condo4** [comment] 2018-10-05 15:13
I rewrite the client like this:
    #include <stdio.h>
    #include <sys/time.h>
    #include <sys/types.h>
    #include <unistd.h>

    #include <nng/nng.h>
    #include <nng/protocol/pubsub0/sub.h>

    int main(int argc, char *argv[])
    {
        char *buf = NULL;
        int rv;
        size_t sz;
        int fd;
        fd_set fds;
        struct timeval tv;

        printf("Test Client\n");

        nng_socket m_sub;

        if((rv = nng_sub0_open(&m_sub)) != 0)
        {
            printf("%s %i", "nng_sub0_open fail", rv);
            return -1;
        }

        if ((rv = nng_dial(m_sub, "tcp://127.0.0.1:6723", NULL, 0)) != 0)
        {
            printf("%s %i", "nng_dial", rv);
            return -1;
        }


        if(argc > 1)
        {
            for(int i = 1; i < argc; i++)
            {
                char item = argv[i][0];
                if(argv[1][0] == '-')
                {
                    printf("Filter accept all\n");
                    if ((rv = nng_setopt(m_sub, NNG_OPT_SUB_SUBSCRIBE, "", 0)) != 0)
                    {
                        printf("%s %i", "nng_setopt", rv);
                        return -1;
                    }
                }
                else
                {
                    printf("Filter add '%c'\n'",item);
                    if ((rv = nng_setopt(m_sub, NNG_OPT_SUB_SUBSCRIBE, &item, 1)) != 0)
                    {
                        printf("%s %i", "nng_setopt", rv);
                        return -1;
                    }
                }
            }
        }
        else
        {
            printf("Filter accept nothing\n");
        }


        sz = sizeof(fd);
        if(nng_getopt(m_sub, NNG_OPT_RECVFD, &fd, &sz) != 0)
        {
            printf("%s %i", "nng_getopt", rv);
            return -1;
        }

        FD_ZERO(&fds);
        FD_SET(fd,&fds);
        tv.tv_usec = 0;
        tv.tv_sec  = 10;

        while(1)
        {
            rv = select(fd+1, &fds, NULL, NULL, &tv);
            if(FD_ISSET(fd,&fds))
            {
                if ((rv = nng_recv(m_sub, &buf, &sz, NNG_FLAG_ALLOC | NNG_FLAG_NONBLOCK)) != 0)
                {
                    if(rv == NNG_EAGAIN)
                    {
                        printf("EAGAIN\n");
                        continue;
                    }
                }
                printf("message... %c\n", buf[0]);
                nng_free(buf, sz);
            }
            else
            {
                printf(".");
            }
        }

        return 0;
    }

So, I can call it with many filter, or - to use "" filter, or no filter:
"client 1" -> ok
"client 2" -> ok
"client 3" -> fail
"client 1 2" -> ok
"client 2 3" -> fail
"client 1 3" -> fail
"client 1 2 3" -> fail
"client -" -> fail (all message)
"client" -> ok (no message)

The issue seem to be here each time I "match" the last message

**Comment by condo4** [comment] 2018-10-05 15:14
The new code base:
[TestNNG.tar.gz](https://github.com/nanomsg/nng/files/2450879/TestNNG.tar.gz)

**Comment by gdamore** [comment] 2018-10-11 18:21
I have not forgotten you -- I will look at this in the next day or so.

**Comment by gdamore** [comment] 2019-03-10 06:39
Pub/Sub got a significant set of updates recently.  Please retest... absent feedback I will close this.

**Comment by gdamore** [comment] 2019-04-16 18:39
Closing due to lack of feedback from submitter, and not reproducible on my end.

**Closed by gdamore** 2019-04-16 18:39 UTC
Labels: feedback
