### ISSUE TITLE
nng_fini hangs with simple http server

### ISSUE THREAD

**Issue by philippegorley** [nanomsg/nng#918] opened 2019-04-09 21:22 UTC
## NNG & Platform details.

Commit c3e06266
Platform: Ubuntu 18.04.2

## Expected Behavior

Program finishes cleanly.

## Actual Behavior

Program hangs when calling nng_fini using atexit.

## Steps to Reproduce

```
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>
#include <stdio.h>
#include <stdlib.h>

static void ping(nng_aio* aio) {
    nng_http_res* resp;
    nng_http_conn* conn = nng_aio_get_input(aio, 2);

    nng_http_res_alloc(&resp);
    nng_http_res_set_status(resp, NNG_HTTP_STATUS_OK);
    nng_http_res_set_header(resp, "Content-Type", "text/plain; charset=UTF-8");
    nng_http_res_set_data(resp, "pong", 4);

    nng_http_conn_write_res(conn, resp, aio);
    nng_http_res_free(resp);
}

int main(void) {
    atexit(nng_fini);

    nng_http_handler* handler;
    nng_http_server* server;
    nng_url* url;

    nng_url_parse(&url, "http://localhost:9999");
    nng_http_server_hold(&server, url);

    nng_http_handler_alloc(&handler, "/ping", ping);
    nng_http_handler_set_method(handler, "GET");
    nng_http_server_add_handler(server, handler);

    nng_http_server_start(server);

    nng_url_free(url);

    const char cmd[] = "curl -w '\\n' -X GET localhost:9999/ping";
    system(cmd);

    nng_http_server_del_handler(server, handler);
    nng_http_handler_free(handler);
    nng_http_server_stop(server);
    nng_http_server_release(server);

    return 0;
}
```

I've removed all error checking for clarity (I didn't get any errors). If I remove the call to nng_fini, the program completes successfully. From a quick investigation, nng seems to block at nni_reap_drain.

Am I missing anything?

**Comment by gdamore** [comment] 2019-04-11 19:32
Something must be preventing the reap from completing -- there's a reaper thread that must be blocked trying to release the resource.  I will need to investigate further.

**Comment by gdamore** [comment] 2019-04-12 05:23
I actually have a theory that the problem is related to threading.  In order for the reaper to *finish*, the reaper thread has to be permitted to run.  The question is, does the atexit() call run while the program is still multithreaded?

What happens if you sleep for a second or so before returning from main()?

(Adding another wrinkle, I wonder whether it would make a difference if you explicitly called exit(), rather than waiting for main() to return... I'm really not sure what the sequence for thread shutdown is, and it's probably platform specific.)

One thing you can try, if you're able (I'm not at present, as I am in the middle of switching environments and my normal POSIX environment isn't available to me) is to see if you can get a stack backtrace at the time of the hang -- it would be informative to find out if the reaper thread is still alive, and if so, what it is doing.  It may be waiting on a lock, or it may be in a continuous spin waiting for some condition to occur that never will.  Either of those would definitely be a bug in NNG.

**Comment by philippegorley** [comment] 2019-04-12 14:39
> I actually have a theory that the problem is related to threading. In order for the reaper to _finish_, the reaper thread has to be permitted to run. The question is, does the atexit() call run while the program is still multithreaded?

Not sure if this might answer the question, but calling nng_fini manually (just before returning from main) doesn't make a difference.

> 
> What happens if you sleep for a second or so before returning from main()?

It still hangs. I've tried sleeping various amounts of time with no success.

> 
> (Adding another wrinkle, I wonder whether it would make a difference if you explicitly called exit(), rather than waiting for main() to return... I'm really not sure what the sequence for thread shutdown is, and it's probably platform specific.)

I'm not sure what the sequence is either. Calling `exit(0)` instead of `return 0` makes no difference.

> 
> One thing you can try, if you're able (I'm not at present, as I am in the middle of switching environments and my normal POSIX environment isn't available to me) is to see if you can get a stack backtrace at the time of the hang -- it would be informative to find out if the reaper thread is still alive, and if so, what it is doing. It may be waiting on a lock, or it may be in a continuous spin waiting for some condition to occur that never will. Either of those would definitely be a bug in NNG.

I'll see what I can do, but it may take a while before I can get back to this.

**Comment by philippegorley** [comment] 2019-04-13 15:58
I found that the program blocks at `nni_cv_wait(&reap_empty_cv);` in `nni_reap_drain`. In the first pass through the loop, if that makes a difference.

The backtrace looks something like:
```
#0 nni_reap_drain       in src/core/reap.c                                                                                                                                                                   
#1 http_server_sys_fini in src/supplemental/http/http_server.c                                                                                                                                               
#2 nni_fini             in src/core/init.c                                                                                                                                                                   
#3 nng_fini             in src/nng.c
```

**Comment by gdamore** [comment] 2019-04-16 06:11
Hmm... maybe we're not waking the reaper up then.  Will look.

**Comment by philippegorley** [comment] 2019-04-16 14:50
> I actually have a theory that the problem is related to threading. In order for the reaper to _finish_, the reaper thread has to be permitted to run. The question is, does the atexit() call run while the program is still multithreaded?

I found this answer on SO: https://stackoverflow.com/a/36488120
```
The atexit() calls will be executed in the main thread after the main thread finishes executing.
```
And in response to whether or not other threads are running at that time:
```
Yes, if you haven't taken steps to stop the other threads and join() them before main() returns.
```

I've added a quick and dirty function that prints the number of threads in a process (the count does indeed drop when a thread is joined):
```
static void thread_count() {
    char buf[128];
    pid_t p = getpid();
    snprintf(buf, sizeof(buf), "ps huH -p %d | wc -l", p);
    system(buf);
}
```
And register it with `atexit`. On my system, it prints 17 after `nng_http_server_hold` and stays at 17 until it eventually hangs.

**Comment by janjaapbos** [comment] 2019-04-16 17:29
I think I am running into the same issue at the http_client side. Connections are not closed.

**Comment by janjaapbos** [comment] 2019-04-16 18:11
I tracked it down to the following code in http_client. If I disable the check for txn->client, the connections are properly closed. 

I don't think txn->client is set at all?

static void
http_txn_reap(void *arg)
{
        http_txn *txn = arg;
        //if (txn->client != NULL) {
        if (1) {
                // We only close the connection if we created it.
                if (txn->conn != NULL) {
                        nni_http_conn_fini(txn->conn);
                        txn->conn = NULL;
                }
        }
        nni_http_chunks_free(txn->chunks);
        nni_aio_fini(txn->aio);
        NNI_FREE_STRUCT(txn);
}

**Comment by janjaapbos** [comment] 2019-04-16 18:28
Not sure if my issue is related to this thread, but I made a pull request with a small fix that solves my client issue.

**Comment by gdamore** [comment] 2019-04-16 18:57
I think @janjaapbos has a different (though possibly similar) issue.

**Comment by gdamore** [comment] 2019-05-19 23:24
Looking at this in more detail, the problem is that the aio that was passed into the handler was never completed.  This is because your callback function needs to call nng_aio_finish() to complete it.  As a result, the shutdown is waiting for that handler's function to be done before it can release the handler.

**Comment by gdamore** [comment] 2019-05-19 23:37
So it's also a bit more complex, because you're trying to reuse the same aio to resubmit the new operation on.  That's not supported.  You would need to have a separate aio structure for sending the reply.  This is kind of complex, and probably more effort than you want to deal with, so the best approach here is change your handler function to:

```
static void ping(nng_aio* aio) {
    nng_http_res* resp;
    nng_http_conn* conn = nng_aio_get_input(aio, 2);

    nng_http_res_alloc(&resp);
    nng_http_res_set_status(resp, NNG_HTTP_STATUS_OK);
    nng_http_res_set_header(resp, "Content-Type", "text/plain; charset=UTF-8");
    nng_http_res_set_data(resp, "pong", 4);

    nng_aio_set_output(aio, 0, resp);
    nng_aio_finish(aio, 0);
}
```

That basically tells the aio framework to send your response directly, rather than having you do it yourself.  (The only reason to do this yourself is if you're going to do some long running operation -- such as sending large amounts of data incrementally.  In that case you really do need to manage your own aio with a separate callback for the incremental send operations.  This usage is somewhat atypical.)

(The other potential case, writing your own http hijacker, e.g. to create your own implementation of websocket or some other protocol handoff, is not supported in the public API at this time.)

**Comment by gdamore** [comment] 2019-05-19 23:37
This isn't a bug in NNG, and I'm closing as such.

**Closed by gdamore** 2019-05-19 23:37 UTC
Labels: http
