### ISSUE TITLE
nng_aio_result return 0 but nng_aio_get_msg return NULL msg

### ISSUE THREAD

**Issue by cr-galrosen** [nanomsg/nng#1325] opened 2020-11-05 16:51 UTC
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
NNG version 1.2.6
Platform Linux CentOS 7 64-bit
We are using c++11

## Expected Behavior
If result on aio object return OK, I expect a message in it.

## Actual Behavior
The message sometimes is NULL and sometimes an invalid address like 0x90.

## Steps to Reproduce
I can't  send a demo code. 
We use req/rep protocol.
Testing connect/disconnect scenario and shutdown.
On disconnect we close the nng sockets but do not release the resources of the AIO. We wait to receive the callback that was registered when allocating the AIO object. On receiving the callback we check the result (the AIO still not closed), the nng_aio_result call return 0, but then a call to nng_aio_get_msg return NULL or invalid msg address, and then a call to nng_msg_body(msg) crash.

**Comment by gdamore** [comment] 2020-11-05 21:54
Is this happening from a callback?  If you're not doing from inside a callback, then you need to use nng_aio_wait() to wait for the operation to be complete.  Until that is done the results in the aio are not valid.

**Comment by gdamore** [comment] 2020-11-05 21:56
Without some kind of demo case, it will be hard to debug -- my strong feeling is that this is a bug in your application not in NNG.  I run many many tests with NNG and a lot of people are using it in production -- and I've never heard about this kind of error.

**Comment by gdamore** [comment] 2020-11-05 21:57
There are also numerous tests for ensuring that *closing* a socket causes the outstanding AIOs to respond correctly (should get NNG_ECLOSED).

**Comment by cr-galrosen** [comment] 2020-11-08 07:34
yes, this is done from within the callback.
I have dual pipe connection between client and server. each holding 2
sockets, Req and Rep. So I have one req/rep connection between client to
server, and the second between server to client.
The user of the client is initiating disconnection by closing both sockets.
at that point both callbacks that associated with the rep and req
connection sockets are called, and in addition the callback that is
associated with the aio of the rep socket. at that point I issue
nng_aio_result and which return ok, but the message is invalid.

Gal.

בתאריך יום ה׳, 5 בנוב׳ 2020, 23:55, מאת gdamore ‏<notifications@github.com>:

**Comment by gdamore** [comment] 2020-11-08 19:28
I really need a reproducer for this case.  That it should be impossible for the message to be unset if the result is zero, and in this particular case (what you describe), it should be NNG_ECLOSED (or if the other side closed the connection maybe NNG_ECONNRESET).

Can you test this with master to make sure it isn't a bug that was fixed.  Also, which socket is getting the NULL message, REQ, or REP?

**Comment by gdamore** [comment] 2020-11-08 19:30
Looking back at this, it looks like most of my big changes to REQ/REP occurred in 1.3.  Please retest v1.3.

**Comment by cr-galrosen** [comment] 2020-11-08 19:32
The REP socket.

בתאריך יום א׳, 8 בנוב׳ 2020, 21:28, מאת gdamore ‏<notifications@github.com>:

**Comment by gdamore** [comment] 2020-11-08 19:44
I'll add a test case to the REP test suite to test closing while blocked in receive.  (We have that test case for send already.)  There are already good tests for closing the *peer*, and those tests all seem to pass fine.  Closing a peer during REP receive should be invisible to the REP consumer anyway - the socket should just drop the message under the hood with no call to the consumer.

**Comment by gdamore** [comment] 2020-11-09 05:43
The test case for this is here: https://github.com/nanomsg/nng/pull/1328/commits/4b23a4212e7e44c916017cca0ebf10d445d40109

As I've indicated, I am unable to reproduce this problem -- I'll need a more concrete demonstrate before I can really have a chance of fixing it.

**Comment by cr-galrosen** [comment] 2020-11-09 20:18
This is not exactly the test case since it does not use a callback.

בתאריך יום ב׳, 9 בנוב׳ 2020, 07:43, מאת gdamore ‏<notifications@github.com>:

**Comment by gdamore** [comment] 2020-11-09 21:58
Can you modify the test case then to use one and post it here?

**Comment by gdamore** [comment] 2020-11-09 22:13
Never mind, I did it for you: https://github.com/nanomsg/nng/commit/ac03c65f4f53265a5ef05d4792e84cf590f5e73e

If you want my further help on this, you're going to have to provide me with a reproducer.  I strongly suspect you have a bug in your own code, rather than a bug in NNG itself.

**Comment by gdamore** [comment] 2020-11-12 08:03
I'm closing this for now.  Feel free to post me with a reproduction case, and I'll be happy to reopen.

**Closed by gdamore** 2020-11-12 08:03 UTC
Labels: feedback
