### ISSUE TITLE
INFINITE lock during IPC listen/dial unit tests

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#126] opened 2017-10-20 21:56 UTC
Blocking on this code in the *win_thread.c* file:

```C++
void
nni_plat_cv_wait(nni_plat_cv *cv)
{
	(void) SleepConditionVariableSRW(&cv->cv, cv->srl, INFINITE, 0);
}
```

With what appears to be a pending [cv->srl (SRWLock)](http://msdn.microsoft.com/en-us/library/windows/desktop/ms686304.aspx) lock.

As per [prior](117) discussion, I've verified that address are changing with every section "iteration", i.e. depth first leaf visitation in Catch parlance.

```
addr: ipc:///tmp/nng_ipc_test_12461
addr: ipc:///tmp/nng_ipc_test_12462
addr: ipc:///tmp/nng_ipc_test_12463
```

**Comment by mwpowellhtx** [comment] 2017-10-20 22:06
@gdamore Well, for giggles, I will structure a C style approach using the same arrangement of sections and see what I get.

**Comment by mwpowellhtx** [comment] 2017-10-20 22:17
@gdamore And using a similar Catch structure, I get the following output, and blocks.

```
addr: ipc:///tmp/nng_ipc_test_12461
addr: ipc:///tmp/nng_ipc_test_12462
addr: ipc:///tmp/nng_ipc_test_12463
```

**Comment by mwpowellhtx** [comment] 2017-10-20 22:21
@gdamore I pushed my latest code, including the improved Catch sections. Run with section name "[abc]" for C++ isolation, and "[def]" for C isolation.

**Comment by mwpowellhtx** [comment] 2017-10-20 22:37
@gdamore I should also clarify, so far the section refactoring is only for the IPC, but I intend to refactor to better support the other transports as well, TCP, TCP6, etc, along these same lines.

**Comment by gdamore** [comment] 2017-10-20 22:39
Please try this program:

```
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "nng.h"

int main(int argc, char **argv)
{
	nng_dialer d;
	nng_listener l;
	nng_socket s1;
	nng_socket s2;
	nng_msg *m1;
	nng_msg *m2;
	int rv;

	rv = nng_pair_open(&s1);
	assert(rv == 0 && s1 > 0);

	rv = nng_pair_open(&s2);
	assert(rv == 0 && s2 > 0);

	rv = nng_listener_create(&l, s1, "ipc:///tmp/somewhere");
	assert(rv == 0 && l > 0);
	
	rv = nng_dialer_create(&d, s2, "ipc:///tmp/somewhere");
	assert(rv == 0 && d > 0);

	rv = nng_listener_start(l, 0);
	assert(rv == 0);

	rv = nng_dialer_start(d, 0);
	assert(rv == 0);

	rv = nng_msg_alloc(&m1, 0);
	assert(rv == 0);

	nng_msg_append(m1, "hello", 6);

	rv = nng_sendmsg(s1, m1, 0);
	assert(rv == 0);

	rv = nng_recvmsg(s2, &m2, 0);
	assert(rv == 0);

	nng_msg_free(m2);

	nng_close(s1);
	nng_close(s2);
}
```

I'm not interested at this point in debugging your code.

**Comment by gdamore** [comment] 2017-10-20 22:39
You can compile that with C++, but you probably have to add the missing return (0) at the end.

**Comment by gdamore** [comment] 2017-10-20 22:40
You could also instrument your code to show "listening at %s", addr, and likewise for "dialing".  That would probably be more informative.

**Comment by gdamore** [comment] 2017-10-20 22:55
Btw, if you wanted to, you could replaace the separate listener and dialer creation and start steps with just nng_listen and nng_dial calls.  End result should be the same.

**Comment by mwpowellhtx** [comment] 2017-10-20 23:08
What is the nni* call doing to shake things looks from the blocked CV?

**Comment by gdamore** [comment] 2017-10-20 23:12
Listeners and dialers should not close their IDs if they want to remain open!  They are normally closed automatically with the socket they are owned by.  (You can close them manually if you really want to, which is one of the reasons we give back a handle to them.)

If you look around somewhere, you will see nni_cond_wake() or nni_cond_wake1().  These are the things that wake up condition variables.  I am assuming you are familiar with condition variables?  That's intrinsic to the code.

**Comment by mwpowellhtx** [comment] 2017-10-20 23:17
Yes, I've used CV's before in conjunction with mutexes, in fact to protect threaded message queues.

So... If I call the nni*, which I do not think I should have to do, will that shake things loose for the listen/dial section to sudden "work"?

**Comment by gdamore** [comment] 2017-10-20 23:18
At this point I have no other insight, other than that your test code isn't executing the way you *think* it's executing.  One suggestion you might try would be to strip out all the other test cases other than the one you are interested in.

At this point, I'm closing this (again?) ... you'll need to debug your program.

I cannot say this strongly enough -- I think trying to copy my test programs is the cause of much grief and heartache.  There are little gotchas throughout, they access internals, they do crazy things to exercise edge cases and ensure that timing behaviors are what I think they should be, they do weird multithreaded things, and they use a goofy execution order.

It would be *far* better, IMO, for you to construct your own test programs, based on your own understanding of how your library is supposed to work, focusing on exercising the combination of the internals of *your* library (not nng), and your public facing API (and documented behaviors).

**Comment by gdamore** [comment] 2017-10-20 23:19
You should NOT call the condition variable directly!!!

**Closed by gdamore** 2017-10-20 23:18 UTC

**Comment by mwpowellhtx** [comment] 2017-10-20 23:20
Well, you're going to be stuck with a Windows IPC bug then until the sleep
thingy is fixed. I've demonstrated the addresses can function, and so on.
What's left is to explain what the nni* call is doing to shake things loose
for the next pass through the test cases.

**Comment by mwpowellhtx** [comment] 2017-10-20 23:21
You are saying I'm calling the CV. I am not. The code is blocking on the CV.

**Comment by gdamore** [comment] 2017-10-20 23:22
Furthermore just signaling the cv will not help you because the *condition*
associated with that has not occurred.  In fact my code is careful to cope
with spurious wake ups.

**Comment by mwpowellhtx** [comment] 2017-10-20 23:33
I'm not interested to signal **any** CVs. From a consumer POV, I shouldn't
need to be calling the nni* call at all, either. As per the NNG API, that's
the whole point, it is **internal**. So, something is broken there, and all
indications that I can determine are pointing to that being the culprit.

**Comment by gdamore** [comment] 2017-10-20 23:41
The problem is that I don't have a test case that reproduces it without all the extra baggage that I don't have time to debug right now.

**Comment by mwpowellhtx** [comment] 2017-10-20 23:53
Yes, I appreciate that. I'm working on correcting my fixtured approach so
"simpler" Catch-friendly test cases to help with this.

I'm sorry this is frustrating. I'm not playing dumb here, I want to help
troubleshoot it. I am as mystified, until it becomes reasonable, as you are.

I will keep you posted when I have the test cases sorted out a bit better.

**Comment by gdamore** [comment] 2017-10-21 00:00
Btw, some things that will cause that condition variable to wake:

1) Actually completing the connection.  With named pipes, we can't use overlapped I/O to establish the connection -- so there is a worker thread that should be blocked in CreateFileA.
The function it is running is nni_win_ipc_conn_thr().  This is the client side connection.  (The server side *is* overlapped in contrast.  Gotta love Windows.)

2) Closing the underlying client endpoint.  (Closing the server endpoint will not do it, because
the client keeps trying to reconnect.)  This should result in NNG_ECLOSED.

3) Closing the client socket (which implicitly just closes the client endpoint).

4) If CreateFileA (which uses OPEN_EXISTING btw) returns an error (like ERROR_NOT_FOUND), then that will wake it too, resulting in something like NNG_ECONNREFUSED.  Killing the server socket (close) will probably result in this, but I've not carefully tested this case (I don't think -- maybe I did.)
