### ISSUE TITLE
nng_recv deadlock on client side in repreq/pair0/pair1 mode?

### ISSUE THREAD

**Issue by ilyaevseev** [nanomsg/nng#570] opened 2018-07-03 01:57 UTC
## NNG & Platform details.

* OS = Fedora28 64bit
* nng cloned from github on 25-jun-2018

## Expected Behavior

* each recv() on client side receives message from appropriate send() on server side

## Actual Behavior

* client stops on recv()
* deadlock happens only when connections between client and server are not persistent (for example, established and closed on the each loop iteration). single persistent connection works fine.

## Steps to Reproduce

* See https://github.com/ilyaevseev/nng-deadlock/ for complete code.

**Comment by gdamore** [comment] 2018-07-03 05:16
Thanks, I think there are some issue in the connection management code.

Can you see if the same issue reproduces with 5ecea06b1f39a93735e8b2f711b125d0b1a84d16 --
I think this may be a regression in the code.

**Comment by gdamore** [comment] 2018-07-03 05:16
Ah, I see you cloned from that date -- although TZ is sensitive.

**Comment by ilyaevseev** [comment] 2018-07-03 13:44
The latest commit in my nng clone is:

```
commit 5ecea06b1f39a93735e8b2f711b125d0b1a84d16 (HEAD -> master, origin/master, origin/HEAD)
Author: Garrett D'Amore <garrett@damore.org>
Date:   Fri Jun 15 12:50:03 2018 -0700

    fixes #539 Feature request: customizable http error page
```

But this commit affects http-related things only.
nng-deadlock uses ipc.

**Comment by gdamore** [comment] 2018-07-03 16:01
There are a couple of later commits, but actually you're using what I would have considered the safest commit.  I'll do some more research, but it might take a little bit -- I have a certain other paying customer demanding my attention first. 

Having said that, I see that you're calling nng_send immediately after listen.  The problem with that is that the loopsock might not actually be ready at the time listen returns -- listen fires off a background thread that accepts incoming connections.

The sockets should redial, and reconnect and self heal in this case, but the default timeouts can be long.  I recommend setting the NNG_OPT_RECONNMINT and NNG_OPT_RECONNMAXT on your sockets to a small value (say 100 or even 10).

I'll play more with this later.  I'm fairly sure that this is simply connection establishment getting in the way.  If its a real deadlock and not just something taking longer than you think it should, that will turn up too.

**Comment by ilyaevseev** [comment] 2018-07-04 03:11
I've tested nng-deadlock with all previous nng releases from 0.2.0 to 0.9.0 and deadlock happens on all versions.

**Comment by gdamore** [comment] 2018-07-04 04:57
I started looking at this earlier today. I will have an answer for you
tomorrow. Stay tuned.

**Comment by gdamore** [comment] 2018-07-04 05:11
I'm pretty sure I know what the problem is but I want to run a couple of
tests to confirm.

**Comment by gdamore** [comment] 2018-07-04 15:10
Ok, I've confirmed it now.  The problem is that you are closing the socket down without giving sufficient time for traffic to transmit to the peer.  close() is instantaneous, and does not include any sort of lingering or flushing of buffers to the remote peer.

The solution is to inject a short delay (100 msec) before calling closing.  I made the following changes to your program, and then the problem was fixed:

```
index 49642e6..279d160 100644
--- a/nng-deadlock.c
+++ b/nng-deadlock.c
@@ -10,6 +10,7 @@
 #include <nng/protocol/reqrep0/rep.h>
 #include <nng/protocol/pair0/pair.h>
 #include <nng/protocol/pair1/pair.h>
+#include <nng/supplemental/util/platform.h>

 #include "mystuff.c"

@@ -70,10 +71,12 @@ void run_server(void)
                nng_free(recvbuf, recvsz);
                printf("server pass %d: free done.\n", pass);

+               nng_msleep(100);
                nng_call("server:xxx:close",  nng_close(loopsock));
                printf("server finished pass %d\n", pass);
        }

+       nng_msleep(100);
        nng_call("server:ctl:close",  nng_close(ctlsock));
 }
```

**Comment by gdamore** [comment] 2018-07-04 15:10
As this isn't a bug in NNG, but merely an application bug and misunderstanding, I'm closing this for now.  We should follow up with additional documentation for nng_close to make this concern clearer.

**Closed** 2018-07-04 15:11 UTC

**Comment by SG7** [comment] 2018-07-05 02:17
I am afraid that this type of programming error is quite frequent. We have
seen it a few times already.

The following is not perfect but possible workaround  is to provide a
default second argument for hidden nng_msleep(sleep_time);

inside the nng_close.

ref: https://gustedt.wordpress.com/2010/06/03/default-arguments-for-c99/


Well, I do not like macros myself.

**Comment by ilyaevseev** [comment] 2018-07-06 09:19
> The problem is that you are closing the socket down without giving sufficient time for traffic to transmit to the peer.

What is sufficient time? 100ms? or 200ms? Or 250ms?
Is it the safe way to calculate it for guaranteed message loosing?

> close() is instantaneous, and does not include any sort of lingering or flushing of buffers to the remote peer.

When connection is closed by remote side, it would be fine for nng_recv() to return NNG_ECONNREFUSED or NNG_ECLOSED instead of deadlocking.

Optionally, it should be good for nng_close() to keep connection until all data are flushed to receiver (or do it as separate function named nng_flush()).

**Comment by ilyaevseev** [comment] 2018-07-06 11:05
BTW, nng_recv() in subscriber is deadlocked by publisher's termination even when publisher and subscriber are connected via TCP. Is it difficult to detect that TCP connection is closed by remote side? :-)

**Comment by gdamore** [comment] 2018-07-06 13:43
The thing is you are misunderstanding how nng sockets work.  Think of them
as virtual sockets with perhaps many connections.underneath to perhaps many
peers.

The fact that there is no error passed up when a peer disconnects is a
feature not a bug. Peers usually reconnect or new peers will connect. The
blocking recv waits until any message is received. This makes writing code
for services super easy as you don't have to think about underlying
connections.

In terms of the wait, for all reasonable connections 100ms is usually
enough. Add more if you have very deep queues (very large messages) or very
long latency networks.

I have been thinking about designs to support draining the queues - eg
lingering in TCP.  I may add that back in later.  (We had some support for
this in the past but it was often broken and can't work in all situations
so I removed it.)
