### ISSUE TITLE
Anchor (jump) links broken in documentation

### ISSUE THREAD

**Issue by paddor** [nanomsg/nng#1745] opened 2023-12-29 18:31 UTC
Low priority, but I noticed that anchor links are missing the `#anchor` part. For example on [1], the link in line "[Raw](https://nng.nanomsg.org/man/tip/nng.7.html) mode sockets ignore all these restrictions." does not include the `#raw_mode` part, even though the source [2] mentions it.

[1] https://nng.nanomsg.org/man/tip/nng_rep.7.html 
[2] https://github.com/nanomsg/nng/blob/master/docs/man/nng_rep.7.adoc?plain=1#L53

**Comment by gdamore** [comment] 2023-12-30 16:08
This is indeed correct.  I think the problem is that tool I use to create the website is dropping the anchors.  I'll have to look.

**Comment by gdamore** [comment] 2023-12-30 16:12
Yeah, it's not *my* tool, but probably the Go libasciidoc package that is getting this wrong.

**Comment by gdamore** [comment] 2024-01-02 04:56
I filed https://github.com/bytesparadise/libasciidoc/issues/1112 to track this with libasciidoc.

**Comment by gdamore** [comment] 2024-02-24 19:11
There were other problems -- libasciidoc was failing to handle index links (not just ignore them, but emitting even hidden index terms in the formatted document.)

I've fixed this by switching back to regular asciidoctor.

Unfortunately it seems that libasciidoc is just not quite ready for the most demanding use cases, and the NNG docs are fairly demanding.

Anyway its fixed now.

**Closed by gdamore** 2024-02-24 19:11 UTC
Labels: docs
